### ISSUE TITLE
The Roles tab lacks the Blacksmith labor

### ISSUE THREAD

**Issue by PatrikLundell** [Dwarf-Therapist/Dwarf-Therapist#1]
Inherited from Splinterz version. Not critical as you can get at the labor from e.g. the Labors Full tab, but annoying as Roles is my main labor assignment tab...

**Comment by cvuchener** [comment]
resources/game_data.ini contains a "Metalsmith" role using skill 29 (Blacksmithing), but it does not show. It looks like it is read correctly by GameDataReader. The bug must come from somewhere else.

**Comment by cvuchener** [comment]
It is missing from resources/default_gridviews.dtg.

Should I rename the "Metalsmith" role to "Blacksmith"?

**Comment by PatrikLundell** [comment]
Personally I find Blacksmith to be a better name, but it's more important to consistently use the same name in all places it appears (e.g. the Labors Full tab, but I don't know if that's the only other place).

**Comment by cvuchener** [comment]
And it is ambiguous with the [Metalsmith](http://dwarffortresswiki.org/index.php/DF2014:Metalsmith) profession.

**Comment by PatrikLundell** [comment]
A very compelling reason to change it throughout, in my view.
