### ISSUE TITLE
Role preference errors

### ISSUE THREAD

**Issue by feelotraveller** [Dwarf-Therapist/Dwarf-Therapist#118]
Preferences for armour pieces are matching 'Clothing (any)' and not matching 'Armour (any)'.  For example Greaves are showing as a match for Clothesmakers but not for Armoursmiths.  Additionally clothing items (other than those that are confusingly armour) are not displaying a match at all on the gridviews.  Hoods for example do not appear/match on the grid, but are correctly displayed in the dock and the tooltip.

Separately, with less gravity and with more structural reason, there is a grammatical issue with the display of preferences for plant parts.  Currently, for example, Mango Tree Fruits is displayed rather than Mangos.  It is decidedly odd and not how DF displays it in vanilla.  Understandably some difficulties arise re: Strawberry Plants and Strawberry Fruits (or would that currently be displaying as Strawberry Plant Fruits - I see Tomatillo Plant Fruit here) but one or the other should probably display as simply Strawberries.  It is similarly odd to see Sweet Potato Plants which while perhaps technically correct from the perspective of the code is not what we call the edible thing we eat in real life, how it gets displayed in native dwarf fortress or referred to on the wiki.

Thanks for your time. (p.s. version 40.1.1)

**Comment by cvuchener** [comment]
If I create "Clothing (any)" and "Armor (any)" columns it works correctly. I must have make an error when updating the default role flags. Do you have any custom role with these preferences?

I'll ignore the food preference name issue for now. Food preferences aren't really implemented yet. When it will be done, some name may be different from the game (like the meats that are not specific enough). I should keep your fruit remark in mind though. Strawberries preference are PLANT_GROWTH items with "strawberry plant fruit" material, "strawberries" is the name for the plant growth itself (not the material). PLANT_GROWTH items will need a special treatment.

**Comment by feelotraveller** [comment]
Yes I noticed the issue with customs role initially but checked that it also occurs in defaults.

Deleting and then readding the categories fixes the issue for custom roles. :smiley:

**Comment by cvuchener** [comment]
I accidentally inverted the values for armor and clothing in ce9a403. I wanted to keep the same values for backward compatibility but I failed. I could put them back, but that will break custom roles made since this commit.

https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/488ba79831097818afdf706d153d5f3cffc14fac/src/global_enums.h#L158-L159

https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/ce9a403d5541858501be5bf33bddd6096848be77/src/itemsubtype.h#L39-L40

**Comment by feelotraveller** [comment]
Fine by me.  IMO getting the default roles to work right is more important.  An announcement for those users making custom roles should suffice.
