### ISSUE TITLE
Custom role weights broken

### ISSUE THREAD

**Issue by feelotraveller** [Dwarf-Therapist/Dwarf-Therapist#121]
Unable to save the weight of individual Attributes, Traits or Skills (e.g. creativity, mechanic, altruism) as anything other than 1.00.  Weights can be specified as other than 1.00 but on save they are written as 1.00.  This applies to both new roles and editing existing roles.  

However copying then saving existing roles with non-1.00 weighting for attributes, traits and skills works fine.  Also always saved correctly are the weights of individual preferences and categories when not 1.00.

Observed with 40.1.2 release.

**Comment by cvuchener** [comment]
Can you test PR #91? The weight system is redone.

**Comment by cvuchener** [comment]
> Right-clicking on the groups (e.g. Attributes) gave me a menu with 'Reset Default Weight' (or similar, did not note exactly) but that did nothing when the option was selected.

The weight was already set to the default value? It is now explicitly displayed if you use the global default weight or a custom value that may have the same value.

> For the items within each group (e.g. Creativity) there was nothing I could figure out to alter the weight, no right click, no spinner. Adding new items resulted in a weight of 1 in all cases. Tried both new custom roles and editing existing ones.

If I add "Double-click to edit this value." in the status/tool tip, is that enough to understand? Did you try the right click out of habit from the old interface or do you think the contextual menu is a natural place to search for editing a value? I should be able to add a "Edit" action in the context menu, if it helps. I'll experiment with edit triggers and persistent editors too.

**Comment by feelotraveller** [comment]
Ah, I see now double-clicking on the value displays the spinner.  I found this unintuitive.  I did try double-clicking but on the strings rather than the values.  I think a hint either in the tooltip, or maybe better in the bottom panel (where it currently says 'This weight is the importance of...') would help.

**Comment by cvuchener** [comment]
Fixed by #91
