### ISSUE TITLE
Unknown thought report!

### ISSUE THREAD

**Issue by frenchiveruti** [Dwarf-Therapist/Dwarf-Therapist#137]
![imagen](https://user-images.githubusercontent.com/1095997/47194177-be540800-d32c-11e8-82d3-6cec81deabcd.png)

![captura de pantalla 10](https://user-images.githubusercontent.com/1095997/47194162-ada39200-d32c-11e8-9abd-0419a77f1d4d.png)
I guess it's for his aunt expell.

**Comment by cvuchener** [comment]
You are not using the latest version and an unknown thought was already fixed in 41.0.3.

**Comment by frenchiveruti** [comment]
> 
> 
> You are not using the latest version and that unknown thought was already fixed in 41.0.3.

Ah I see, I'm a lazy newb :)
