### ISSUE TITLE
Feature Request: Sort by Migration Wave & Sort by Profession

### ISSUE THREAD

**Issue by clcollins** [Dwarf-Therapist/Dwarf-Therapist#141]
Both options would make it much easier to address new migrants, and see who is doing what.  It was in some version of Dwarf Therapist that I tried over the years, and was a great feature.

Apologies if its already there, and I'm missing it.

**Comment by cvuchener** [comment]
They are still there, I did not touch them. Or do you mean using both at once?

**Comment by clcollins** [comment]
Weird - I am using the Linux RPM from RPMFusion, and it points to this repo in the documentation, and in the Automatic Updates area in DT. 

Maybe the sort is in a different spot that I used to see it.  I would right-click on the area above the Dwarfs names and it would offer the option to sort by migration wave and profession.  Now when I do, I get a menu that says "Sort by..." and has options for age, body size, id and name only.  

Am I just looking in the wrong place?

* version info * 
41.0.2 (Linux)

* RPM info * 
```
Name         : dwarftherapist
Version      : 41.0.2
Release      : 1.fc28
Arch         : x86_64
Size         : 4.7 M
Source       : dwarftherapist-41.0.2-1.fc28.src.rpm
Repo         : @System
From repo    : rpmfusion-nonfree-updates
Summary      : Management tool designed to run side-by-side with Dwarf Fortress
URL          : https://github.com/Dwarf-Therapist/Dwarf-Therapist
License      : MIT
Description  : Management tool designed to run side-by-side with Dwarf Fortress.

```

**Comment by clcollins** [comment]
Well, interesting - I found the dropdown menu near the filter button, which I'd never used before.  That answers my question!  Sorry for the trouble & thanks for your reply!

That will teach me to take a few years off playing!
