### ISSUE TITLE
How to get dark theme in ubuntu? [solved]

### ISSUE THREAD

**Issue by matt32106** [Dwarf-Therapist/Dwarf-Therapist#144]
I installed kvantum to change the default QT theme to a dark one. It works for regular QT apps, e.g. VLC. However when I launch dwarftherapist (./dwarftherapist in the terminal), it keeps using its eye-killing white theme and not the QT default theme. How do I tell dwarftherapist to use the default QT theme in linux (ubuntu 18.04 in my case)?

**Comment by cvuchener** [comment]
How did you get Dwarf Therapist? The AppImage version ships its own version of Qt including the platform and style plugins, so it does not integrate well with your distribution, that's the price for working everywhere. If you compiled DT using your system libraries or installed a package for your distribution, it should use your default theme.

If all else fails, there are command line options for forcing the platform or style plugins. See [here](https://doc.qt.io/qt-5/qapplication.html#QApplication) and [here](https://doc.qt.io/qt-5/qguiapplication.html#QGuiApplication).
