### ISSUE TITLE
Unit listing shows true name of vampires

### ISSUE THREAD

**Issue by TV4Fun** [Dwarf-Therapist/Dwarf-Therapist#145]
[This bug has existed since at least 2012](http://www.bay12forums.com/smf/index.php?topic=102200.0), but I thought I should create an issue for it. If a unit is a vampire under a false name, the name that shows up for them in DF is different from the name that shows up for them in DT, which is a bit of a giveaway. This is with DF 0.44.12, DFHack 0.44.12-r1, DT 41.0.3, on Windows 10.

**Comment by cvuchener** [comment]
This happens when the vampire has a nickname ? I don't think I have a save with a vampire to check right now.

I'm quite sure vampires without nicknames used to work.

**Comment by TV4Fun** [comment]
In my fortress, I have not given nicknames to anyone, but am still seeing different names in DF and DT. Here is my save http://dffd.bay12games.com/file.php?id=14153. The vampire here is the mayor, who in DF shows up as Goden Udibbekar, but in DT shows up as Rigoth Bavastlogem.

**Comment by cvuchener** [comment]
It works for me on Linux. It may be a memory layout issue on windows only, I'll try later.

**Comment by cvuchener** [comment]
I see the fake identity when testing with df 0.44.12 win64, but the game crashes when I try to load the save with the win32 version.

**Comment by TV4Fun** [comment]
Odd, after closing and reopening DF and DT, now I am seeing the mayor's fake name in DT. I guess this is an intermittent problem. Will update if I see it again.

**Comment by falcn** [comment]
On a Mac, DT shows true name and true kill list of a vampire that arrived undercover. The latter is even bigger giveaway. No nickname was assigned.

**Comment by cvuchener** [comment]
Any error or warning in the log?

If you have DFHack, select the vampire and run `:lua !dfhack.TranslateName(dfhack.units.getVisibleName(dfhack.gui.getSelectedUnit()))` in the console, does it shows the correct name?

**Comment by lmilne96** [comment]
Running `:lua !dfhack.TranslateName(dfhack.units.getVisibleName(dfhack.gui.getSelectedUnit()))` shows the unit's fake name (i.e. the one that DT should be showing).

**Comment by cvuchener** [comment]
Could the fake identity be created just after the dwarf arrive? But then DFHack wouldn't work either.

I don't get why you need to re-open, I checked the code it completely reloads the unit and the historical figure.

Did you check the log for errors or warnings?

**Comment by cvuchener** [comment]
> I don't get why you need to re-open, I checked the code it completely reloads the unit and the historical figure.

Actually the identity vector is cached, so that's the issue. It was loaded before the new dwarf with a fake identity arrive. When the dwarves are later reloaded, the identity vector is not and the new fake identity is not found.
