### ISSUE TITLE
version numbers are missing on macOS

### ISSUE THREAD

**Issue by core-code** [Dwarf-Therapist/Dwarf-Therapist#164]
when selecting the latest macOS version, no version number is displayed in the macOS Finder.

both the CFBundleVersion and CFShortVersionString entries are missing in your Info.plist file

**Comment by cvuchener** [comment]
What are the expected values for these entries?

**Comment by core-code** [comment]
i've downloaded the latest macOS version which seems to be '41.0.2' so the expected entry for both of these would be '41.0.2'

**Comment by cvuchener** [comment]
I cannot test macOS myself. If you are able to test the patches from PR #165, that would help.

**Comment by core-code** [comment]
thanks i can confirm PR #165 fixes this.

<img width="179" alt="Screenshot 2019-06-17 at 17 00 47" src="https://user-images.githubusercontent.com/1261954/59614704-88685d00-9121-11e9-8ae3-7ceaee60ca66.png">
