### ISSUE TITLE
Military Tactician role not listed

### ISSUE THREAD

**Issue by Svistoplyaz** [Dwarf-Therapist/Dwarf-Therapist#173]
Hello, I have noticed that I can see that my dwarf is Military Tactician using the window shown below on the image. But I can not find any way to see Tactician skill, not in the military tab, not in other skills tab, nowhere. Can you help me out, please?

Version used: Version 41.1.0

![изображение](https://user-images.githubusercontent.com/12596916/64485024-fa30de00-d21a-11e9-9ee8-bc490b0b2b33.png)

**Comment by cvuchener** [comment]
You can add any skill in a custom grid view. Use the "Windows" > "Docks" > "Grid Views" to create and edit grid views.

If you create a grid view that you think would be better for everyone than the default ones, you can make a suggestion.

**Comment by Svistoplyaz** [comment]
Thank you!
