### ISSUE TITLE
crash on start - OSX Catalina

### ISSUE THREAD

**Issue by ninchistudios** [Dwarf-Therapist/Dwarf-Therapist#177]
Installed as directed. Authorised with control-run.  Starts then crashes immediately after admin password auth request with:

`2019-Nov-21 23:33:43.578 INFO	core	Dwarf Therapist "41.1.1" starting normally. 
[src/dwarftherapist.cpp:215] (setup_logging)`

`2019-Nov-21 23:33:43.578 INFO	core	Runtime QT Version 5.13.2 [src/dwarftherapist.cpp:216] (setup_logging)`

`2019-11-21 23:33:43.883 DwarfTherapist[10588:504417] The application with bundle ID io.github.dwarf-therapist.DwarfTherapist is running setugid(), which is not allowed. Exiting.`

`macbox1:Applications james$ 
`

**Comment by cvuchener** [comment]
Does it happen on older version of macOS?

**Comment by AntonVLA** [comment]
same problem

**Comment by cvuchener** [comment]
I can find other reports with similar error messages on the web, but no explanation of why it is happening. At this point, DT is root, why kill it when it tries to drop privileges?

**Comment by leemcdougall** [comment]
Is it something to do with Catalina not liking 32 bit apps anymore?

**Comment by cvuchener** [comment]
Current releases are 64 bit only. It is more like a weird security feature that forbids applications running as root to use seteuid. I don't really understand why.

**Comment by ninchistudios** [comment]
> Does it happen on older version of macOS?

It didn't happen on Catalina with the older version bundled with the Lazy Mac Pack. I have no way of testing it on a non-Catalina Mac.

**Comment by lethosor** [comment]
What DT version was the older one?

**Comment by ninchistudios** [comment]
> What DT version was the older one?

39.2.1

**Comment by cvuchener** [comment]
You can try [v41.0.2](https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v41.0.2), if you want something a little newer that should work the same.

Can someone with this issue try to recompile from source and check if it is still happening? Then, if the issue is still present, try reverting e1fcd558a6649620a9792096ab651f5ebb2e9f26 (`git revert e1fcd55`) and recompile again.

Or if someone knows the rules for using seteuid on macOS, that would be helpful too.

**Comment by sandlst** [comment]
> Can someone with this issue try to recompile from source and check if it is still happening? Then, if the issue is still present, try reverting [e1fcd55](https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/e1fcd558a6649620a9792096ab651f5ebb2e9f26) (`git revert e1fcd55`) and recompile again.

Just tested; the issue is still present but reverting that commit does seem to fix it.

**Comment by plidauer** [comment]
> Can someone with this issue try to recompile from source and check if it is still happening? Then, if the issue is still present, try reverting [e1fcd55](https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/e1fcd558a6649620a9792096ab651f5ebb2e9f26) (`git revert e1fcd55`) and recompile again.
Can also confirm: after the revert DT started without issues.

**Comment by jecowa** [comment]
Another Mac OS X 10.15 Catalina user is reporting a problem with Dwarf Therapist 41.1.2 not launching on Catalina.

I had him try to run 41.0.2 instead. Version 41.0.2 would launch, but it couldn't connect to Dwarf Fortress. 

link to discussion: https://www.reddit.com/r/dwarffortress/comments/f0t5x9/lite_lazy_mac_pack_updated_for_df_v04702/fh7hoqn/

**Comment by cvuchener** [comment]
I would need the log from the 41.0.2 try. For this version I am not sure where it is, it should be log/run.log somewhere in whatever is the "working directory" of DT (since 41.1.0 it is in ~/Library/Logs).

**Comment by jecowa** [comment]
I see, 41.0.2 looked for memory layouts in the Application Support folder instead of it's built-in memory layouts folder.

**Comment by TV4Fun** [comment]
I can't be 100% sure, but I suspect this is related to [this issue](https://developer.apple.com/forums/thread/702595) where `NSApplication` and `NSWindow` call `issetugid()` and return an error if it's true. From the `issetugid` man page:

> The issetugid() system call returns 1 if the process environment or memory address space is considered “tainted”, and returns 0 otherwise.
>
> A process is tainted if it was created as a result of an execve(2) system call which had either of the setuid or setgid bits
     set (and extra privileges were given as a result) or if it has changed any of its real, effective or saved user or group ID's
     since it began execution.
What's probably happening is that you're dropping root privileges before creating the UI window, and that's causing it to appear "tainted" to the OS. No idea why this ridiculous restriction appears or what a good workaround is. As it relates to config files being owned by root, why not just write to them as root, then you wouldn't have the permission saving issue.

**Comment by cvuchener** [comment]
> No idea why this ridiculous restriction appears or what a good workaround is.

Here, the "taint" is having the saved user id set to 0. DT can become root again by calling seteuid(0) at any time, including from an attacker, so it is a security risk.

> As it relates to config files being owned by root, why not just write to them as root, then you wouldn't have the permission saving issue.

You would still have a root-owned file in your home messing with all other processes trying to interact with it (for example your file explorer).
