### ISSUE TITLE
A fort has not been loaded

### ISSUE THREAD

**Issue by paintchip** [Dwarf-Therapist/Dwarf-Therapist#182]
I can't get DT (41.1.1) to see that I have a fort running on Gentoo (x64) with DF 0.44.12. I have tried the appimage and compiled my own and can't get it to work. I've also run the DF and DT versions from the LNP with the same results (including combinations of LNP and my DF & DT). The terminal usually shows 

ERROR  core    READ_RAW: "Function not implemented" READING 8 BYTES FROM ....

after detecting my DF version and setting the memory layout. I know the post said some versions may be missing memory layout depending on the OS, is that the case here?

I'll do whatever I can to help/contribute if you can help point me in the right direction.

**Comment by cvuchener** [comment]
What is your kernel version? I expect it is newer than 3.2, process_vm_readv should be implemented.

Can you apply this patch and see if the error message changes?

```diff
--- a/src/dfinstancelinux.cpp
+++ b/src/dfinstancelinux.cpp
@@ -112,7 +112,8 @@ USIZE DFInstanceLinux::read_raw(const VIRTADDR addr, const USIZE bytes, void *bu
     struct iovec remote_iov = {reinterpret_cast<void *>(addr), bytes};
     SSIZE bytes_read = process_vm_readv(m_pid, &local_iov, 1, &remote_iov, 1, 0);
     if (bytes_read == -1) {
-        LOGE << "READ_RAW:" << QString(strerror(errno)) << "READING" << bytes << "BYTES FROM" << hexify(addr) << "TO" << buffer;
+        int err = errno;
+        LOGE << "READ_RAW:" << QString(strerror(err)) << "READING" << bytes << "BYTES FROM" << hexify(addr) << "TO" << buffer;
         memset(buffer, 0, bytes);
         return 0;
     }
```

**Comment by paintchip** [comment]
This is my fault. I didn't realize that the READ_RAW function was a kernel call. I am on 4.19.86, but I didn't have config_cross_memory_attach compiled into my kernel and it's apparently not a default in genkernel. It works after adding it. In the unlikely event that someone else is having this problem, the kernel option from menuconfig is found in General Setup >  Enable process_vm_readv/writev syscalls.

Thanks for the help and sorry about that. I'm actually a bit disappointed. I was hoping I would get to help and contribute a bit!
