### ISSUE TITLE
Issue regarding Dwarf-Therapist on a Kali

### ISSUE THREAD

**Issue by UltimateCreed** [Dwarf-Therapist/Dwarf-Therapist#184]
Good day , I seem to be running into the following issue as i run the ./dwarftherapist program.
Here is the output of dwarftherapist.

https://pastebin.com/rHGzBtfg

**Comment by feelotraveller** [comment]
A quick search found this
[https://stackoverflow.com/questions/53355217/genymotion-throws-libssl-conf-so-cannot-open-shared-object-file-no-such-file-o](url)
does that help?

Seems like this is a Kali issue rather than Dwarf-Therapist one.

**Comment by UltimateCreed** [comment]
@feelotraveller that fixed it indeed , just had to reinstall openssl and export the variable
