### ISSUE TITLE
Fails to connect after build

### ISSUE THREAD

**Issue by RonYanDaik** [Dwarf-Therapist/Dwarf-Therapist#186]
Outputs says:
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

Any ideas?
Both DF and MVS2017 project are on D:\ (not a system partition)

MVS was launched as administrator. 

v: 0.44.12

**Comment by cvuchener** [comment]
It may be because you have outdated openssl libraries. Try downloading the newest version: https://indy.fulgan.com/SSL/.

Network is only used for updating memory layouts, it is not essential and you may ignore the error.

**Comment by RonYanDaik** [comment]
But it does not load data from game.

Do i need an original game build? I use LNP (and Therapist in the package works. i guess its standard build, or it somehow was made to be compatible with DFHack?). 

log:

2020-Jan-31 21:58:44.880 INFO	core	attempting to find running copy of DF [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:236] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.887 INFO	core	PID of process is:  16436 [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:242] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.888 INFO	core	PROC HANDLE: 0x688 [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:252] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.890 INFO	core	RAW BASE ADDRESS: 140699411021824 [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:283] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.890 INFO	core	Target EXE was compiled at  "2018-07-07T23:23:57" [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:78] (DFInstanceWindows::calculate_checksum)
2020-Jan-31 21:58:44.891 INFO	core	Setting memory layout for DF checksum "0x5b41215d" [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstance.cpp:1132] (DFInstance::set_memory_layout)
2020-Jan-31 21:58:44.891 INFO	core	Detected Dwarf Fortress version "v0.44.12 (graphics) win64" using MemoryLayout from "C:/Users/Yuri/AppData/Roaming/Dwarf Therapist/memory_layouts/windows/v0.44.12_graphics_win64.ini" [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstance.cpp:1137] (DFInstance::set_memory_layout)
2020-Jan-31 21:58:44.892 INFO	core	GetModuleFileNameEx returned:  "D:\\TEMP_F~1\\PERIDE~1.12-\\Dwarf Fortress 0.44.12\\Dwarf Fortress.exe" [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:316] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.892 INFO	core	Dwarf Fortress path: "D:/TEMP_F~1/PERIDE~1.12-/Dwarf Fortress 0.44.12" [D:\temp_forever\gits\Dwarf-Therapist\src\dfinstancewindows.cpp:319] (DFInstanceWindows::find_running_copy)
2020-Jan-31 21:58:44.892 INFO	core	Checking for layout for checksum:  "0x5b41215d" [D:\temp_forever\gits\Dwarf-Therapist\src\updater.cpp:134] (Updater::check_layouts)

**Comment by cvuchener** [comment]
I don't see any issue in this log. It even finds a memory layout. Is there any error or warning in the log?

**Comment by RonYanDaik** [comment]
dont see any warnings
maybe this:
mincore\com\oleaut32\dispatch\ups.cpp(2125)\OLEAUT32.dll!00007FFE530A3C5B: (caller: 00007FFE530A3DD2) ReturnHr(1) tid(4aa0) 8002801D Library not registered.

How can i trace it to see if it loads items? Where to look?

**Comment by RonYanDaik** [comment]
![image](https://user-images.githubusercontent.com/3350340/73591465-5e6c7b00-44f7-11ea-8485-f183ac503134.png)

so i tried to debug it. the debugger steps to the manifest_loop.exec(); and then stops debugging and runs. 
Hers gif if what i mean. I press here only F10 (step over). The debugger should step on the next line but instead it just runs continues execution.
![debug](https://user-images.githubusercontent.com/3350340/73591509-08e49e00-44f8-11ea-8414-af42e5ade5a6.gif)

**Comment by RonYanDaik** [comment]
I've commented out that line and everything runs now.
There should me more appropriate way to press such error.

**Comment by RonYanDaik** [comment]
> 
> 
> It may be because you have outdated openssl libraries. Try downloading the newest version: https://indy.fulgan.com/SSL/.
> 
> Network is only used for updating memory layouts, it is not essential and you may ignore the error.

where should i put those libs?

**Comment by cvuchener** [comment]
> I've commented out that line and everything runs now.
There should me more appropriate way to press such error.

I you want a simple workaround: disable automatic updates.

I am not sure if the network requests progress when the event loop is not running and so if there can be a race condition here. Rewriting the code to be asynchronous may be the cleanest way to fix that. But that may not be the real issue.

Which version of Qt are you using? I'd like to try reproducing it.

> where should i put those libs?

next to Dwarf Therapist.exe

**Comment by RonYanDaik** [comment]
> Which version of Qt are you using? I'd like to try reproducing it.

QT 5.14.1
