### ISSUE TITLE
Animal Geld status

### ISSUE THREAD

**Issue by cppcooper** [Dwarf-Therapist/Dwarf-Therapist#189]
I have noticed that the geld status doesn't update appropriately in dwarf therapist. I have several gelded dogs, but DT shows none.

DF: v0.44.12
DFHack: v0.44.12-r2
DT: v41.0.3
All software was acquire through the linux lazy newb pack ([LinuxLNP 0.44.12-r03 x64](http://dffd.bay12games.com/file.php?id=13244))

**Comment by cvuchener** [comment]
Which DF version? OS?

**Comment by cppcooper** [comment]
Updated the OP.
Sorry for the bad form of not testing on the latest, I realize there are newer versions of DF and DT, however I did not see anything that could have, presumably, fixed this in any of the release notes. 

Although the newest might, with the update to memory layouts. Again I apologize for not testing on the latest, however that would have required going far out of the way just to test this. Until dfhack pushes a release I will be unable to use any fix anyway so this is more of an attempt to service the DT community.

**Comment by cvuchener** [comment]
Actually it works but only if you have checked "Read Livestock Health Information" in the option dialog. Can you confirm that?

I wonder why this option was added. To avoid cheating by reading detailed health diagnostics? It should be changed so the health information is read anyway but the details may be hidden (or merge it with the cheating option "Always Show Wound Details").

**Comment by cppcooper** [comment]
Yup works. That is really silly that livestock geld status is included in that.. I would never have thought to look for a setting that enables that. By not showing the geld status, DT is priming users for job cancellation alert loops.

**Comment by feelotraveller** [comment]
My very vague memory is that the outcome was a result of someone wanting to see gelded status for animals but not wanting to 'cheat' on the wounds of their dwarfs (and presumably animals).  If I remember the discussion correctly there were also people who did not want see their animal health information at all.

Though neither of these are concerns of mine I think that they are fair enough requests (even if my memory is wrong...).

(The troublesome mechanic, again if I remember correctly, is for DF 'gelded' is a permanent wound.)

**Comment by cppcooper** [comment]
Wouldn't it make more sense to have it enabled by default?
Not at all sure what the data structures look like on the c++ side, but in dfhack's lua interpreter geld status is merely a flag among flags `unit.flags3.gelded` basically right next to `unit.flags3.marked_for_gelding`. Seeing as how marked for gelding is visible in DT by default I would think it should stand to reason geld status should be as well. Perhaps - if I finish updating my dfhack scripts before my week long break is over - I will take a look at the DT code and see if I can't track down the relevant code and conceive a solution.

**Comment by cvuchener** [comment]
> My very vague memory is that the outcome was a result of someone wanting to see gelded status for animals but not wanting to 'cheat' on the wounds of their dwarfs (and presumably animals). If I remember the discussion correctly there were also people who did not want see their animal health information at all.

That was my intuition, but there is already another option for health cheating.

> Not at all sure what the data structures look like on the c++ side, but in dfhack's lua interpreter geld status is merely a flag among flags unit.flags3.gelded basically right next to unit.flags3.marked_for_gelding. Seeing as how marked for gelding is visible in DT by default I would think it should stand to reason geld status should be as well. 

DT uses `unit.body.wounds[i].parts[j].flags2.gelded`, I'll look at the other flag.

**Comment by feelotraveller** [comment]
> Wouldn't it make more sense to have it enabled by default?

Yep.  I think it is an artifact from the historical evolution of the code.

Personally I think that DT should support (only) two settings for the health/wound details:
1) whatever is shown by vanilla DF (default)
2) full health/wound status information for all fortress creatures - visitors, hm? - (toggle on)

(Gelding data would be shown in both sets.)

Limiting displayed information through grid views seems a better approach for people who only want some extra data.

**Comment by cvuchener** [comment]
Looking at how it works currently, I think the best solution is to simply treat animals same way as citizen. And add GELDED as an exception, like SEVERED, as "obvious" wounds that don't require diagnosis. If somehow an animal wound get diagnosed, it will be shown, but that seems fair. Seeing animal wounds will require extra effort anyway since there is no default gridview for animal health.

**Comment by cppcooper** [comment]
For what it is worth, I've noticed the game only checks `unit.flags3.gelded` for deciding whether to put the **x**'s in a creature's name - actually I can't really say "only" I don't know for sure that it doesn't check the body parts also.

As for which it uses to determine whether an animal can reproduce, that I do not know.
