### ISSUE TITLE
Unknown thought

### ISSUE THREAD

**Issue by Majorkite** [Dwarf-Therapist/Dwarf-Therapist#190]
Mousing over for thoughts, shows 'satisfied this is an unknown thought please report it!' Looks like its for having their guild hall petition accepted. Reporting it as requested!
![image](https://user-images.githubusercontent.com/59674650/74904230-66427100-5379-11ea-8205-b95fe4692ac2.png)

**Comment by cvuchener** [comment]
A new thought from 0.47? Do you have dfhack? If so, select the unit with `v` or `u` and type `gui/gm-editor unit.status.current_soul.personality.emotions` in dfhack console and look for the unknown thought. If you cannot use dfhack, could you share the save?

New thoughts were added in https://github.com/DFHack/df-structures/commit/c18cbeb28a8fb4f67e63db0547ac4b221c6903b6 but not identified. If this one of the new thoughts you should report it to https://github.com/DFHack/df-structures too.

**Comment by Majorkite** [comment]
https://drive.google.com/open?id=12zRweQkJku0pdIgAw47kyuMTSkqv6AKr here is the save, the dwarves with the thought are hunters and rangers

**Comment by MaximumZero** [comment]
This is what I came up with.
![DFnewThought](https://user-images.githubusercontent.com/62574693/77369192-647f1b00-6d34-11ea-8f43-b17e93037532.png)
