### ISSUE TITLE
import/save open file dialogs do not appear [macOS 10.15]

### ISSUE THREAD

**Issue by ccaviness** [Dwarf-Therapist/Dwarf-Therapist#195]
Any use of an `Import ...` or other file dialog generating option does nothing. Launching Dwarf Therapist directly in a terminal (`$ ./DwarfTherapist.app/Contents/MacOS/DwarfTherapist`) shows this error on every attempt:

```
2020-03-09 16:38:14.411 DwarfTherapist[73364:648342] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'com.apple.view-bridge': Connection interrupted
```

Some light searching seems to suggest this is a change in macOS 10.15. Perhaps related to requiring sandboxing? Or possibly Qt is using `beginSheetForDirectory` method to open a file browser instead of `beginSheetModalForWindow`? It's unclear what the root cause is.

Tested with latest DT release (41.1.4) as well as one built from `master`. Running on macOS 10.15.3.

**Comment by cvuchener** [comment]
Apparently this was a common issue during Catalina beta. Are you sure you are using the latest version? Same question for Qt.

Try compiling a minimum program:

`main.cpp`:
```c++
#include <QApplication>
#include <QFileDialog>

int main(int argc, char *argv[])
{
	QApplication app(argc, argv);
	QFileDialog::getOpenFileName();
	return 0;
}
```

`filedialog.pro`
```qmake
CONFIG=qt
QT=gui widgets
TARGET=filedialog
SOURCES=main.cpp
```

Use `qmake filedialog.pro` then `make` to build.

If this issue happens with this minimal program please report directly to [Qt bug tracker](https://bugreports.qt.io).

**Comment by cvuchener** [comment]
Does any of the [new builds](https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v41.1.7) help with this issue?

**Comment by ccaviness** [comment]
I see the same issue with all 3, unfortunately.

I suspect this is due to stricter sandboxing in Catalina, and something about DT being launched as the user then setuid to root is perhaps causing the issue?

**Comment by ccaviness** [comment]
On a lark, I launched DT from the command line with `sudo`, and the Import dialog opened up as expected. I didn't test beyond that as I don't have df installed on this machine. This more strongly confirms my suspicion that the problem is when DT launches as the user then changes to uid 0, triggering some sort of security measure new in 10.15.

Also, I managed to get the test code above compiled (after fighting with `brew` then giving up and playing with Qt Creator), and it works successfully. Launching it displays the file chooser dialog.

**Comment by ccaviness** [comment]
It seems some change in the last 6 months has fixed this, as the current build (41.2.1) seems to work as expected. Launch times are pretty slow (couple of minutes), but the import dialogs work and modifications are saved across launches as well.

**Comment by cvuchener** [comment]
I made some minor Qt version updates in 816777f886c1413a7095aee2ddacb9af390350ef. Could that be the reason it works now?

**Comment by ccaviness** [comment]
I'm not sure - since I last tested things I've also upgraded my Mac to macOS 11, so Apple may have made/reverted some change that helped.
