### ISSUE TITLE
Focus tooltip calculation missing 0.47.04

### ISSUE THREAD

**Issue by feelotraveller** [Dwarf-Therapist/Dwarf-Therapist#197]
Not sure of the right words - the picture shows it:

![focus](https://user-images.githubusercontent.com/33111504/76669791-51a47200-65e1-11ea-8343-c9a36a422863.png)

Guessing the underlying dfhack field has moved?  The calculation shows correctly for when using df 44.12 (with same 41.1.5 therapist).

**Comment by cvuchener** [comment]
Open "Thoughts and preference for a dwarf" and refresh DT, is the dwarf focus still invalid?

**Comment by feelotraveller** [comment]
Assuming you mean thoughts and preferences in DF then it remains invalid.

**Comment by cvuchener** [comment]
Please try the new memory layouts from #198.

**Comment by feelotraveller** [comment]
Fixed for me (using v0.47.04_linux64.ini). :+1:
