### ISSUE TITLE
Kill Count

### ISSUE THREAD

**Issue by CompiledMayhem** [Dwarf-Therapist/Dwarf-Therapist#20]
Been using DT 39.0.0 64 bit with DF 0.44.02. My dwarves killed a bunch of trolls and troglodytes but DT isnt showing a kill count or listing the kills in the military tab.

**Comment by cvuchener** [comment]
Could you upload your save? (on [DFFD](http://dffd.bay12games.com/index.php) for example)

I did not play much yet, so I am lacking a save with a more advanced fortress on 0.44.02.

**Comment by CompiledMayhem** [comment]
Sure. I'll will upload the save and some screenshots as soon as I get back the a machine with the save which should be in the next 6-7 hours

**Comment by CompiledMayhem** [comment]
So I try to recreate this issue when I got home by reloaded the same fort, and the kills were there. So I figured I must have forgotten to hit read or something. However after a bit more time on 44.02 I've seen it a couple more times. Annoyingly saving the game and reloading corrects the issue, so passing a save file wont help.

Heres a snippet from DT after a read showing no kills for a dwarf, and the kills list from the game just to prove I wasnt imagining it all.

![image](https://user-images.githubusercontent.com/31015183/33518922-2192a244-d795-11e7-9dba-114996b58e53.png)

**Comment by cvuchener** [comment]
The "Read" button does not reread all the data, it only does a minimal update. It is possible that DT does not update the kill list. I will check that.

Next time it happens, try restarting DT but not DF.

**Comment by CompiledMayhem** [comment]
I think I may have figured out whats going on. It doesnt seem to be counting kills of males. If you take a look at the above screenshots, all kills are male yet zero are shown. Here's another example...
![image](https://user-images.githubusercontent.com/31015183/33524863-31be0cbc-d81c-11e7-9021-573e711f1865.png)
Struggling to screenshot the mouse over text but DT shows three kills, which matches the number of females above.
![image](https://user-images.githubusercontent.com/31015183/33524873-54787724-d81c-11e7-84e6-877e50f5bbbd.png)

I've got save that shows this behavior, see link for file and reproduction steps. http://dffd.bay12games.com/file.php?id=13274

**Comment by cvuchener** [comment]
I can reproduce the bug.

Uploading the save only (folder data/save/region1) would have been enough (and a lot lighter).
