### ISSUE TITLE
New skill in 0.47

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#203]
Reported by @PatrikLundell http://www.bay12forums.com/smf/index.php?topic=168411.msg8126257#msg8126257

 - Riding (136)

**Comment by PatrikLundell** [comment]
Thanks. I'll try to remember to report things here rather than in the thread.

**Comment by PatrikLundell** [comment]
Found Schemer (in DF UI) matching another UNKNOWN migrant's skill. Haven't bothered to look up the number, as it should be in the enum (and I assume you'll check that anyway, rather than rely on the reports being accurate).
