### ISSUE TITLE
Q) what can I do there?

### ISSUE THREAD

**Issue by neo6633** [Dwarf-Therapist/Dwarf-Therapist#207]
![2020-05-06_12-37-26_DwarfTherapist](https://user-images.githubusercontent.com/1337267/81289926-25b5e200-90a2-11ea-8841-ee4c1593d7a0.png)

**Comment by cvuchener** [comment]
Typing text that won't do anything at all. It is not used anywhere in the code. It was added in e89a1def8fd34e1b1dc30275abeb4b1f075a7401 but there is no hint of why splintermind did it, maybe it's just an accident.

I thought about deleting it some time ago, but apparently I forgot.

**Comment by neo6633** [comment]
> 
> 
> Typing text that won't do anything at all. It is not used anywhere in the code. It was added in [e89a1de](https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/e89a1def8fd34e1b1dc30275abeb4b1f075a7401) but there is no hint of why splintermind did it, maybe it's just an accident.
> 
> I thought about deleting it some time ago, but apparently I forgot.

thx for reply :)

**Comment by cvuchener** [comment]
I reopen so I remember to do it this time.
