### ISSUE TITLE
Unknown Thought

### ISSUE THREAD

**Issue by Quartich** [Dwarf-Therapist/Dwarf-Therapist#208]
**satisfied** this is an unknown thought, please report it!

thought shown in-game was " She felt satisfied at work." (x2)

![bug report ingame](https://user-images.githubusercontent.com/40511780/81360855-de801f00-90aa-11ea-97a5-c7582d509cbc.PNG)
![bug report therapist](https://user-images.githubusercontent.com/40511780/81360868-e344d300-90aa-11ea-9e48-990a982183ab.PNG)

**Comment by cvuchener** [comment]
It must be the guildhall petition. A release is coming soon with the fix.

Duplicate of #190
