### ISSUE TITLE
Checksum missmatch 

### ISSUE THREAD

**Issue by Eluminae** [Dwarf-Therapist/Dwarf-Therapist#214]
Hello all,

I'm trying to package use Therapist but I got a checksum problem.

It seems Therapist looks for a 0x49f07c37 checksum for dwarffortress-0.47.04 but my installed version checksum seems 0x49f07c37.

![screenshot of missmatch checksum popup](http://dav.misterbanal.net/8dbce29a-f823-40dc-813e-b5e88127ec15.png)

My context is:

I updated and packaged DwarfFortress and DwarfTherapist on the VoidLinux distro:

* https://github.com/Eluminae/void-packages/blob/8aeedf32ac2bbe95fda54a549fdcd0258fadb026/srcpkgs/dwarffortress/template
* https://github.com/void-linux/void-packages/blob/1fc546cd74db53116c62fa1b622ba503ef2293fb/srcpkgs/dwarftherapist/template

As you can see, we don't patch the game and we only add a minor setup/starter script and force LD_PRELOAD env vars so, my questions are:

* Is this last DwarfFortress 0.47.04 version checksum bugged in DwarfTherapist?
* How is computed the DwarfFortress process checksum ?
* What in the DwarfFortress package make checksum to differs ?

Ty a lot by advance !

PS: As you can see, I created a work-around seding the checksum but I really think this is a bad and unmaintenable solution.

**Comment by cvuchener** [comment]
It is the md5 of the executable (libs/Dwarf_Fortress). Why did you change it? I don't understand what you're doing with the post_install part either.

Also for the dwarffortress package, you can delete libgcc/libstdc++ from DF directory instead of preloading the system ones.

**Comment by Eluminae** [comment]
> It is the md5 of the executable (libs/Dwarf_Fortress) truncated to 32 bits. Why did you change it?

Okay thanks a lot! It seems xbps-src (the void package builder) got a strip step. I disabled them on my "Dwarf Fortress" exe and now it preserve the good checksum.

> I don't understand what you're doing with the post_install part either.

Here I just add the two dist ptrace utils scripts to the package.

> Also for the dwarffortress package, you can delete libgcc/libstdc++ from DF directory instead of preloading the system ones.

Right, I encoutered a df forum that spoke about it too. I'll intergrate this fix too cause it seems cleaner than this preload sed.

**Comment by Eluminae** [comment]
I now have fantastics and workings packages. Thanks you !
