### ISSUE TITLE
How to run Dwarf Therapist as non root user in Ubunutu 20.04?

### ISSUE THREAD

**Issue by kylemiller3** [Dwarf-Therapist/Dwarf-Therapist#217]
I cannot use DT without running as root. If I do I get "A fort has not been loaded." Is there a way to work around this issue?

**Comment by cvuchener** [comment]
https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/master/dist/ptrace_scope/README.md

I recommend using [patch_df_ptracer](https://raw.githubusercontent.com/Dwarf-Therapist/Dwarf-Therapist/master/dist/ptrace_scope/patch_df_ptracer).

**Comment by kylemiller3** [comment]
Thank you
