### ISSUE TITLE
After return from raid, squad membership incorrectly reported

### ISSUE THREAD

**Issue by georgevtucker** [Dwarf-Therapist/Dwarf-Therapist#218]
2 10-member squads dispatched on raid. Upon return, squad_1 appears in DT as empty except for squad leader. However, in DT on right-click "Add to squad..." squad_1 reported as full. 

DT 41.1.7 version, win64
DF 0.47.04
![squad-full-but-empty](https://user-images.githubusercontent.com/34581548/85576079-18c76080-b606-11ea-8b35-fc2ab8885564.png)

Not bothering with a save because I assume this is a known issue? But I don't see it reported elsewhere. Pls let me know if a save would be helpful.

**Comment by cvuchener** [comment]
Are the missing members shown in DT outside the squad or are they completely missing from DT unit list ? If it is the later, can you check the logs (*File* → *Open log directory*) for the missing dwarves names and see if there is a reason they were omitted.

Yes, a save would help.

**Comment by georgevtucker** [comment]
Missing members are shown in DT outside the squad -- the first of the two scenarios you proposed.

[Save here](https://georgevtucker.com/wp-content/uploads/2020/06/region2.zip). 
Here's the log: [dwarftherapist.log.txt](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/4826259/dwarftherapist.log.txt)

Affected units:

- Dwarf (0x000001e4a4041cb0) name:'Gobsmasher' Uristtithleth Berlitez Arros id:12355 histfig_id:17671
- Dwarf (0x000001e4a404a920) name:'Thieftaker' Uthirreg id:13297 histfig_id:17947
- Dwarf (0x000001e4a401e170) name:Sazir Lolokshed id:12282 histfig_id:17641
- Dwarf (0x000001e4a3ff8950) name:Zon Omristdeler id:11208 histfig_id:17074
- Dwarf (0x000001e4a4020990) name:Adil Ushattishis id:12334 histfig_id:1766
- Dwarf (0x000001e4a3f96160) name:Dumed Absamfikod id:10597 histfig_id:16683
- Dwarf (0x000001e4a3f93940) name:Medtob Istamingish id:10482 histfig_id:16642
- Dwarf (0x000001e4a3f8acd0) name:Uvash Ducimtomus id:10383 histfig_id:16580
- Dwarf (0x000001e4a40571c0) name:Obok Nishtan id:13412 histfig_id:17967

Thanks!

**Comment by georgevtucker** [comment]
I just reloaded the save and reopened Dwarf Therapist and the issue was resolved. I'm marking this closed so you don't waste time investigating what seems to've been a non-reproducible error -- will open if I can reproduce (with new save files!).

Thanks!
