### ISSUE TITLE
Missing goal/dream in 47.04 (attaining rank in society)

### ISSUE THREAD

**Issue by Bakutomo** [Dwarf-Therapist/Dwarf-Therapist#220]
I've got a dwarf with the goal: "She dreams of attaining rank in society."
This isn't recognised by Dwarf Therapist and doesn't appear in the personality tooltip for that dwarf.

It looks like it just needs to be added to the [goals] list in [/resources/game_data.ini](https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/v41.1.7/resources/game_data.ini#L1392) but I don't know how to find out its ID number.

**Comment by Bakutomo** [comment]
I managed to find out its ID by trial-and-error modifications to game_data.ini. The following works:

    14\id=13
    14\name="rank"
    14\desc="dreams of attaining rank in society"

**Comment by cvuchener** [comment]
There is actually two new goals according to dfhack: https://github.com/DFHack/df-structures/blob/b67b3fa4b02f834dc76a2e1eae21136e0be089f7/df.units.xml#L198-L199

The best way to find new values is looking at them using dfhack (either command line or gui/gm-editor).

**Comment by ryanbennitt** [comment]
This should be fixed now. I've added the three missing goals in PR #224 among with ability to group dwarfs by their goal.
