### ISSUE TITLE
"Jubilation" thought is not recognised

### ISSUE THREAD

**Issue by IvanSanchez** [Dwarf-Therapist/Dwarf-Therapist#221]
I just finished building a temple, and some of my dorfs are experiencing the feeling of [jubilation](https://en.wiktionary.org/wiki/jubilation), but Therapist doesn't know about that feeling.

![imagen](https://user-images.githubusercontent.com/1125786/88471115-49e8c880-cf05-11ea-8fcc-10ccc55dfd5f.png)

![imagen](https://user-images.githubusercontent.com/1125786/88471128-6e44a500-cf05-11ea-8c9e-35aed4a958e9.png)

I have stashed a savefile in which that dorf is feeling that way. It's ~60MiB so ~~won't attach to this bug report, but it's available on request~~ I'll upload it to DFFD at my earliest convenience.

**Comment by lethosor** [comment]
It's actually the "establishment of a temple" bit that's unrecognized by DT. This is a relatively [new thought](https://github.com/DFHack/df-structures/blob/389ffde5a96b3c8263c0c2a2376e387aa2343fad/df.unit-thoughts.xml#L1668) (as of 0.47.04, its ID is 253, or 0xFD). 

On second glance, it looks like support for this was added in c61b5e78b18cf3174d0c7297cec92af76496a1d6, which is part of DT v41.1.7 - are you using this version of DT (or newer)?

**Comment by IvanSanchez** [comment]
> On second glance, it looks like support for this was added in [c61b5e7](https://github.com/Dwarf-Therapist/Dwarf-Therapist/commit/c61b5e78b18cf3174d0c7297cec92af76496a1d6), which is part of DT v41.1.7 - are you using this version of DT (or newer)?

No, I'm running 41.1.4 (from a lazy newb pack)

**Comment by lethosor** [comment]
Ok, this is essentially a duplicate of #190, then. You'll probably have to upgrade your pack or bug your pack's author about upgrading DT. You might be able to copy in the newer game_data.ini, but I'm not sure where exactly it would go (you could try looking for an existing game_data.ini in a DT data folder and replacing it).

**Comment by IvanSanchez** [comment]
Understood :smile:  . Sorry for the duplicate issue.
