### ISSUE TITLE
Roles are not calculated properly

### ISSUE THREAD

**Issue by esavier** [Dwarf-Therapist/Dwarf-Therapist#223]
I have weird issue regarding Roles view (or Military-alt for example)
All my dwarfes seems to have 50% in everything, including red and black values which means those are either not calculated or not displayed properly.

It may be issue on my side but i do not how to debug this.
currently on windows 10, latest build of DT

**Comment by cvuchener** [comment]
Can you assign labors to your dwarves? If there is no labor capable dwarf, role statistics don't work.

Otherwise check the logs for errors. Open *File* → *Open log directory*, and search for ERROR or WARNING in the log file.

**Comment by esavier** [comment]
- I can not find any errors nor warnings in the logs,
- I could set any labor on any dwarf, ony thing that was not working properly was role calculation values.

I actually fixed it and it now works properly. I changed date format (windows currency format and stuff like that) since i remembered that between last working configuration and now i changed some stuff in the format settings, namely period to comma and added separators. Restarted PC and now it works as intended. Since DT is based on Qt, that may have been an issue, but i can not reproduce it right now. I included the logs from previous runs

[dwarftherapist.log.3.txt](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/5012717/dwarftherapist.log.3.txt)
[dwarftherapist.log.4.txt](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/5012718/dwarftherapist.log.4.txt)
[dwarftherapist.log.2.txt](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/5012719/dwarftherapist.log.2.txt)

**Comment by cvuchener** [comment]
> I actually fixed it and it now works properly. I changed date format (windows currency format and stuff like that) since i remembered that between last working configuration and now i changed some stuff in the format settings, namely period to comma and added separators. Restarted PC and now it works as intended. Since DT is based on Qt, that may have been an issue, but i can not reproduce it right now. I included the logs from previous runs

Does the issue reappear if you change your locale again? If so, please tell me the exact settings.

> edit: ah, and i reseted whatever settings i was able to reset

Having all role weights to 0 could cause your issue (and it would be the expected behavior, so not really an issue), I don't anything else should. If any other setting breaks the roles, I'd like to know which one.

**Comment by esavier** [comment]
okay, i will test it out again today, and update you on any progress
thanks! ❤️

**Comment by esavier** [comment]
Hey,
I was trying for few days, and i can not reproduce it, i have no idea why the problem started in the first place, but i tried messing with everything i changed between games.

Please, lets close it for now, and i will either reopen or issue new bug when i will manage to replicate the issue
