### ISSUE TITLE
Big Sur Windows Not Created

### ISSUE THREAD

**Issue by voreisthescore** [Dwarf-Therapist/Dwarf-Therapist#240]
Launching the latest release and DF0.47.05 on Big Sur 11.1, DwarfTherapist opens however does not create any windows, In Activity Monitor it is shown as "Not Responding". Checking the logs however you do see whatever underlying logic is working. 
[dwarftherapist.log](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/6099853/dwarftherapist.log)

The above is when the game isn't running. With the game running, same effect however we get:
[dwarftherapist.log](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/6099876/dwarftherapist.log)

Have tried with the three supplied versions of QT

**Comment by cvuchener** [comment]
Your log says you are running 41.1.6, this is not the latest version.

**Comment by voreisthescore** [comment]
Upgraded the app by replacing the one in the Applications folder. Apologies. After Removing it completely and then copying from the disk image it worked.
