### ISSUE TITLE
DF freezes after opening the custom role editor dialog.

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#242]
http://www.bay12forums.com/smf/index.php?topic=168411.msg8259577#msg8259577

@jecowa, I need more information about how `task_suspend` may fail. If you can compile DT, could add the following line in `dfinstanceosx.mm` and see if you can find it in the log when reproducing this bug?

```diff
diff --git a/src/dfinstanceosx.mm b/src/dfinstanceosx.mm
index e35ad6e9..c1f173c5 100644
--- a/src/dfinstanceosx.mm
+++ b/src/dfinstanceosx.mm
@@ -100,6 +100,7 @@ bool DFInstanceOSX::attach() {
 
     result = task_suspend(m_task);
     if ( result != KERN_SUCCESS ) {
+        LOGE << "task_suspend failed:" << result;
         return false;
     }
     m_attach_count++;
```

**Comment by jecowa** [comment]
Ahhhhh! I think I am compiling Dwarf Therapist for the first time!

**Comment by cvuchener** [comment]
Use `-DBUILD_DEVMODE=ON` on cmake command line (or edit your CMakeCache.txt) and don't try to install it, just run the binary from the build directory.

**Comment by jecowa** [comment]
The "task_suspend failed:" never turns up in the logs: [Dwarf Therapist log 1.txt](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/6176821/Dwarf.Therapist.log.1.txt)

After this I tried adding some more of those LOGE lines in other places and remaking just to make sure I was doing it correctly.

**Comment by cvuchener** [comment]
If you comment (add `//` at the beginning of the line) this line:

https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/589da28282636792d96efdf6e5cf29bfcaa2ac1b/src/dfinstance.cpp#L1103

Is task_resume called as many times as task_suspend?

**Comment by jecowa** [comment]
Yes. 631850 suspends and 631850 resumes. Also Dwarf Fortress didn't freeze when I opened the New Custom Role feature.
