### ISSUE TITLE
[Linux] DT all of a sudden doesn't connect to running game / doesnt find running game

### ISSUE THREAD

**Issue by Bl4ckh34d** [Dwarf-Therapist/Dwarf-Therapist#247]
[dwarftherapist.log](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/7005981/dwarftherapist.log)
All of a sudden dwarf therapist can't find running games anymore.
![grafik](https://user-images.githubusercontent.com/63246613/129870705-8ddbe3de-eede-4aab-846a-dc738a247934.png)
No idea what happend.

OS: Ubuntu 20.04
DFHack: 0.47.05-r2
Starterpack: PyLNP 0.14a 
DT: 41.2.2

**Comment by cvuchener** [comment]
>  Starterpack: PyLNP 0.14a

PyLNP is not a pack, only the launcher. You should report the issue to your pack maintainer.
