### ISSUE TITLE
incoming merchants can be assigned to squads

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#248]
I'm lending this space quickly: There's one specific issue. If you request workers from a vassal via a mission, the incoming merchants can be assigned to squads although they shouldn't be (and cannot be in vanilla).

_Originally posted by @MatiasOETamminen in https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/212#issuecomment-903275047_

**Comment by cvuchener** [comment]
DT should only assign citizens and mercenaries. Are they only the merchant's mercenaries? Or any kind of merchant unit can be assigned?

**Comment by MatiasOETamminen** [comment]
It's the new arrivals that are gained by requesting workers from a vassal site (native residents of vassal, not people expelled from the mother-fort).

**Comment by cvuchener** [comment]
I don't know this game mechanic. I would need to test it. Can you upload your save? Or do you know of an already uploaded save where this can tested?

On [the wiki](http://dwarffortresswiki.org/index.php/DF2014:Tribute), I read:
> If you successfully sent a squad on a mission to conquer a neighbouring site, it will also be incorporated into your holdings. Your conquering forces will remain onsite as administrators and occupiers, though you may call (most of) them back by requesting workers with your messenger. The site will also send tribute to you, in the form of various items and livestock. 

Doesn't that mean that the "workers" should be your old squad?

**Comment by MatiasOETamminen** [comment]
I don't currently have a save where I have this situation but if I get to such a situation, I will upload my save.

There are (I think) three types of people living at these vassal sites I'm talking about:
1. the old squad, as you mentioned, if it's a conquered site
2. any ex-workers you've sent away (e.g. tantruming ones) to that site
3. People not originating from your main fortess, especially if it's not a conquered site but a organically founded hillocks.

It's the type 3 I'm referring to.

**Comment by feelotraveller** [comment]
I wonder if this is linked to the bug mentioned on the [Holdings](https://dwarffortresswiki.org/index.php/DF2014:Holding) DFwiki page that prevents requested workers in the base game from being able to be assigned labours. 

Anyway the [bug report](https://www.bay12games.com/dwarves/mantisbt/view.php?id=10921) contains links to two saves on DFFD which have requested workers that are problematic in their labour assignation in DF.  I assume that they should show the squad assignment behaviour as detailed above in this thread.

(It's not clear to me if those workers should/are intended to be able to be assigned to squads in the base game or not. A question to ToadyOne in the Future of the Fortress thread on the Bay12 forums might be in order before making any change to DT?)

**Comment by cvuchener** [comment]
Thank you feelotraveller. I tried psychowico's save. The two merchant cannot be chosen from the military screen unless I change their profession. Even if it is a DF bug to send merchants when workers are requested, I think I should add a profession-based check for military (and labor?) assignments.

DFHack structures have a "can_assign_labor" attribute on professions but sadly no "can_assign_military".

**Comment by feelotraveller** [comment]
Nice work!

Yes to adding in the checks.  But I think it could be useful to have an override (like the current 'Allow Labour Settings on Anyone') for allowing assignation to squads illegally.  One use case is to work around what are thought to be bugs, although I've heard of people assigning labours to children and gremlins - more power to them if they want to play that way. ;)

**Comment by cvuchener** [comment]
> But I think it could be useful to have an override (like the current 'Allow Labour Settings on Anyone') for allowing assignation to squads illegally.

Could I use the same option so it also applies to squad, or does it need to be separate option?

@lethosor Do you think it is worth adding a `can_assign_military` attribute for `profession` enum in df-structures?

**Comment by feelotraveller** [comment]
> Could I use the same option so it also applies to squad, or does it need to be separate option?

Using the same option seems fine to me.

**Comment by lethosor** [comment]
> @lethosor Do you think it is worth adding a `can_assign_military` attribute for `profession` enum in df-structures?

I'd be open to it if you think it would be useful for other tools too.
