### ISSUE TITLE
dwarftherapist cannot connect to running _supported_ DF version

### ISSUE THREAD

**Issue by stamasd** [Dwarf-Therapist/Dwarf-Therapist#251]
Running on Funtoo (Gentoo derivative) 64-bit with DF 0.47.05 freshly downloaded from bay12 a few days ago, dfhack latest version installed from github (fresh compile) and dwarftherapist also installed from here, fresh compile.

Launched DF, generated a world, embarked, then launched dwarftherapist.

Error message: 

I'm sorry but I don't know how to talk to this version of Dwarf Fortress!
Checksum: 0x65dbcb22
Please re-connect when Dwarf Fortress has been started and a fort has been loaded.

However the details window clearly lists the game version with this checksum as supported.
Supported Versions:
v0.43.05 linux32 (0x652a8b5c)
v0.43.02 linux (0x3c048bd0)
v0.42.06 linux (0x6ffd260f)
v0.43.03 linux (0xdf4ffde3)
v0.43.01 linux (0x26c01df8)
v0.43.05 linux64 (0xaf8cc86c)
v0.44.02 linux64 (0xd4ac0c09)
v0.44.02 linux32 (0x26bb7790)
v0.44.03 linux32 (0x14c2726e)
v0.44.03 linux64 (0x530e3fef)
v0.44.04 linux32 (0x73d7441b)
v0.44.04 linux64 (0xef636f3e)
v0.44.05 linux32 (0x33e2bc29)
v0.44.05 linux64 (0xcfe90090)
v0.44.06 linux64 (0x2d56bb1f)
v0.44.06 linux32 (0x55a8419c)
v0.44.07 linux32 (0x2e215961)
v0.44.07 linux64 (0xdbbc2359)
v0.44.08 linux32 (0xa36e4f13)
v0.44.08 linux64 (0x31d71455)
v0.44.09 linux32 (0xe6aff8f7)
v0.44.09 linux64 (0x621e2c82)
v0.44.10 linux32 (0xcdfce5ff)
v0.44.10 linux64 (0xb2fb37d7)
v0.44.11 linux64 (0xe05a549a)
v0.44.11 linux32 (0xbba69c9e)
v0.44.12 linux32 (0xae16f7bf)
v0.44.12 linux64 (0x4b10f9cc)
v0.47.01 linux64 (0x9e19d527)
v0.47.01 linux32 (0x3ab868a2)
v0.47.02 linux32 (0xff640dd5)
v0.47.02 linux64 (0x6bf21f5f)
v0.47.03 linux64 (0x0f184a43)
v0.47.03 linux32 (0xd64e00ff)
v0.47.04 linux32 (0xefb418c2)
v0.47.04 linux64 (0xedb951bf)
v0.47.05 linux32 (0x9b111ecd)
v0.47.05 linux64 (0x65dbcb22)

No matter how many times I retry, it fails to connect with the same error message. Shutting down DF and dwarftherapist and relaunching both does not fix anything. It still cannot connect.

I am including a link to a screenshot.
https://i.postimg.cc/FRgQCYbg/errordt1.png

**Comment by stamasd** [comment]
Here is also the view from the terminal where I launched dwarftherapist
https://i.postimg.cc/rwQjjMt0/errordt2.png

**Comment by cvuchener** [comment]
The full log is stored in ~/.cache/dwarftherapist/log/dwarftherapist.log, you don't need to take screenshot, you can copy the text instead. Do you find any other errors or warnings before the "lost connection to DF" one ?

Are you running DT from the build directory, or did you install it ? Is your XDG_DATA_HOME (~/.local/share by default) writable ?

**Comment by stamasd** [comment]
I'm running DT from the same directory as DF. ~./local/share is writable, by my user only (700). 
I'm attaching the log
[dwarftherapist.log](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/7490837/dwarftherapist.log)

**Comment by cvuchener** [comment]
Does creating the directory ~/.local/share/dwarftherapist/memory_layouts/linux fix the issue?

**Comment by stamasd** [comment]
Yes it does! At first launch, DT complains of no memory layouts found - but when I click 'retry" it downloads layouts and runs. After shutting DT down and relaunching, it straight works without any errors.
Thank you!

**Comment by cvuchener** [comment]
So there are two things to fix:
 - [ ] create the memory layout directory if it does not exist already
 - [ ] don't list a version as supported if downloading the memory layout failed
