### ISSUE TITLE
Feature Request: Flip x and Y axis

### ISSUE THREAD

**Issue by Dherman3607** [Dwarf-Therapist/Dwarf-Therapist#253]
I find it REALLY hard to read the jobs from the top, where there's many options for filtering down the list of dwarves.

**Comment by cvuchener** [comment]
And then you'll have a really hard time reading names. I know that column headers are not ideal, but changing them is difficult and I am not sure I can really do better. Anyway I am not making huge change until I know how the next DF release redefines what DT is.

If it is the number of columns that is bothering you, you may create several smaller custom gridviews.
