### ISSUE TITLE
Social-Alt is wrong and Traits is incomplete.

### ISSUE THREAD

**Issue by Erquint** [Dwarf-Therapist/Dwarf-Therapist#267]
![image](https://user-images.githubusercontent.com/4364856/208247656-e022b109-fcfb-445a-84f3-df09ee182d24.png)
1. The Social-Alt gridview tab displays four useful dark columns.
However, each of those reads value and description of the wrong trait.
Assertiveness → Stress Vulnerability.
Cooperation →  Ambition.
Self-consciousness → Cheer Propensity.
Straightforwardness →  Confidence.
2. Additionally, the Traits gridview tab lacks three of those four: Cooperation, Self-consciousness and Straightforwardness.

**Comment by cvuchener** [comment]
It seems Self-consciousness and Straightforwardness don't exists after DF 0.34. Cooperation has become a belief. So "Traits" seems to be correct. I never paid much attention to Social-Alt but it looks outdated.

I understand it is supposed to show social skill and the personality traits linked to it. Based on the [DF2014 wiki page](http://dwarffortresswiki.org/index.php/DF2014:Personality_trait), I guess the grid view should have:
 - **Conversationalist**
   - FRIENDSHIP? (+)
   - LEISURE_TIME? (+)
   - _BASHFUL_ (-)
   - _GREGARIOUSNESS_ (+)
 - **Intimidator**
   - POWER (+)
   - HARMONY (-)
   - TRANQUILITY (-)
   - _DISCORD_ (+)
   - _ASSERTIVENESS_ (+)
 - **Flatterer**
   - TRUTH (-)
   - _FRIENDLINESS_ (+)
 - **Persuader**
   - ELOQUENCE (+)
   - _ASSERTIVENESS_
 - **Consoler**
   - STOICISM (-)
   - _DISCORD_ (-)
   - _CRUELTY_ (-)
   - _SWAYED_BY_EMOTIONS_ (+)
 - **Comedian**
   - MERRIMENT (+)
   - _HUMOR_ (+)
 - **Pacifier**
   - PEACE (+)
   - _DISCORD_ (-)

Some are beliefs others are facets (in _italic_), some facets are used for several skills. This would add a lot of columns to this gridview. As user of it, what do you think should be done?

**Comment by Erquint** [comment]
I think explaining my use case would be relevant.
When deciding whom to appoint to the expedition leader position, I'd consult a corresponding [wiki page](http://dwarffortresswiki.org/index.php/DF2014:Expedition_leader) — note the version. I would see the table on the page and note all the relevant skills, traits and attributes.

*Pages like that tend to include the traits you claim as missing in this version a lot. I honestly find myself confused at that discrepancy now.*

And then I noticed that the Social-Alt. tab compiles all the social skills and attributes that appear in those tables. Kinda assumed that's what the tab's intended purpose was.

**Comment by feelotraveller** [comment]
> Pages like that tend to include the traits you claim (correctly, I presume) as missing in this version a lot.

Many (all?) of the 0.34 pages were copied across to what would become the 0.47 page without revision.  Some still contain out of date information since no one has updated them.  (Compare the 0.34 and 0.47 Expedition Leader pages...)  Tratis are a case in point.

I do agree that that social-alt tab is not very useful in its current form and could undergo revision or abandonment.  (It's not one that I ever use,)  My preference would be to abandon/delete it but to make sure that the information it would contain is conveyed in other, more categorised, tabs - beliefs under beliefs, facets under facets, attributes under attributes, skills under other skills (if not covered elsewhere) and so on.

My two cents.

**Comment by cvuchener** [comment]
Expedition Leader page looks as outdated as the Social-Alt gridview.

> Does this make that whole paragraph that precedes all those tables misleading now?

I think the personality is still important in how a dwarf interacts with others and thus which social skills are trained. It's just that the personality traits have changed after 0.34.

> Are beliefs optional? What sets them apart?

You should read the [DF2014 Personality page](http://dwarffortresswiki.org/index.php/DF2014:Personality_trait), I don't know more than what's written there.

The fact that the Social-Alt gridview meaning is not obvious would make me agree with feelotraveller's suggestion to remove it. I should also add the missing Beliefs gridview. And I encourage you to create your own custom gridviews with the exact columns you actually need.

The link between social skills and personality traits may actually work better with roles. If social skills deserve default roles, they could be added (#88).

**Comment by Erquint** [comment]
> I think the personality is still important in how a dwarf interacts with others and thus which social skills are trained. It's just that the personality traits have changed after 0.34.

Are the weights set for default roles in DT reflective of that currently? I was getting confused why they differ from wiki but wasn't sure which side dropped the ball.

> the Social-Alt gridview meaning is not obvious

I would cautiously argue that its meaning seemed to be to compile all the traits relevant to noble roles until those changed and DT failed to adapt yet. It's take it or leave it now, whether you wanna update it to be useful for that again. I'm in support of feelotraveller's suggestion with all its stipulations considered.

> And I encourage you to create your own custom gridviews with the exact columns you actually need.

Thanks for the reminder! I totally forgot that was a feature.

In terms of the actual game, that whole system creates a bit of a duality of best dwarf to fill a position, since either you want a noble that's best as is or you want a noble that has a good capacity to become exceptional. Something to ponder on for separate feature.

***

I think the main point of this here issue to keep in mind is the interface showing trait values and description of other wrong traits. Some (sequentially-assigned?) pointers need correcting.

**Comment by feelotraveller** [comment]
> Are the weights set for default roles in DT reflective of that currently?

The current default roles do not use personality traits.  (Needs someone to do the research and put in the effort to revise the roles.)  In general the roles accurately reflect the skills and attributes useful for them, although judgement calls have been made. If you notice anything seemingly out of place then let us know. The expedition leader is probably the roughest but is the best attempt we've had at a summary.  Feel free to make a better one!

> In terms of the actual game, that whole system creates a bit of a duality of best dwarf to fill a position, since either you want a noble that's best as is or you want a noble that has a good capacity to become exceptional. Best role suggestions would then depend on which of those approaches you're looking from. Something to ponder on for a separate feature.

Under 'Options -> Roles' you can specify the default weights for skills, attributes and preferences (plus others currently unused).  The (default) defaults for these weightings favour current skill - this was the outcome of an old discussion - but it is easy enough to see potential by turning down the skill (and maybe preference) weight to see who will be the 'best' dwarf when at max skill.  That said I often favour going for preferences, at least where those preferences are decisive/important ones.  A dwarf who likes beds, for example, is a good candidate for a carpenter regardless of their current skill or the potential of their attributes.
