### ISSUE TITLE
Can Anyone Check This? Population Addresses

### ISSUE THREAD

**Issue by BenjaminHei** [Dwarf-Therapist/Dwarf-Therapist#268]
Edit: This is for the Steam Edition.

I think I identified the location of number of population (all) and population (adults).

0x1DA19CC - Population (All)
0x1DA19D8 - Population (Adults Only)

I'm working on a Python script for getting an entire population's innate abilities and wanted to share this info on the bay12 forums but I haven't been approved, so I figured i'd share here if it is useful to the DT project.

```
from pymem import *
from pymem.process import *

mem = Pymem("Dwarf Fortress.exe")
module = module_from_name(mem.process_handle,"Dwarf Fortress.exe").lpBaseOfDll

print(mem.read_int(module + 0x1DA19CC))
```

This returns an accurate result over a few different saves.

Sorry if this is an inappropriate place to put this, I'm fairly new to GitHub and a fledgling python coder.

**Comment by ab9rf** [comment]
i can confirm that dfhack has 141d18cc as what we call `ui.tasks.population`
we have 14da19db as an unknown, so i can't confirm that that's the number of adults, but it's plausible

**Comment by BenjaminHei** [comment]
> i can confirm that dfhack has 141d18cc as what we call `ui.tasks.population` we have 14da19db as an unknown, so i can't confirm that that's the number of adults, but it's plausible

Thanks for the quick reply! Would you mind sharing some guidance as to the disparity between values from 0x1DA19CC and 141d18cc? They are almost similar but not quite

**Comment by ab9rf** [comment]
> > i can confirm that dfhack has 141d18cc as what we call `ui.tasks.population` we have 14da19db as an unknown, so i can't confirm that that's the number of adults, but it's plausible
> 
> Thanks for the quick reply! Would you mind sharing some guidance as to the disparity between values from 0x1DA19CC and 141d18cc? They are almost similar but not quite

sorry, 141d18cc was a typo, the correct value is 141da18cc. the reason for the leading 140000000 is that's the default base address for dwarf fortress prior to ASLR, and so that's what we generally list in our (that is, dfhack's) address database. in reality we have this particular structure mapped out as offsets from its base address, which Toady calls `plotinfo`. `plotinfo` (which for historic reasons we call `ui`) starts at 141da1670. this particular field is at offset +0x14c of a larger structure that itself starts at offset +0x210 in `plotinfo`, or at 0x141da1670 + 0x210 + 0x14c

**Comment by BenjaminHei** [comment]
> > > i can confirm that dfhack has 141d18cc as what we call `ui.tasks.population` we have 14da19db as an unknown, so i can't confirm that that's the number of adults, but it's plausible
> > 
> > 
> > Thanks for the quick reply! Would you mind sharing some guidance as to the disparity between values from 0x1DA19CC and 141d18cc? They are almost similar but not quite
> 
> sorry, 141d18cc was a typo, the correct value is 141da18cc. the reason for the leading 140000000 is that's the default base address for dwarf fortress prior to ASLR, and so that's what we generally list in our (that is, dfhack's) address database. in reality we have this particular structure mapped out as offsets from its base address, which Toady calls `plotinfo`. `plotinfo` (which for historic reasons we have been calling `ui` but which we have agreed to change to match Toady's names going forward) is ia 0x9100 byte structure starting at 0x141da1670. this particular field is at offset +0x14c of a larger structure that itself starts at offset +0x210 in `plotinfo`, or at 0x141da1670 + 0x210 + 0x14c

Thank you so much! So 14da19db I noticed changed values whenever I expelled dwarves along with 141da18cc but it was always off by like 14 from the value, and when I looked closer I noticed there were 14 children in the fort, so I assumed it meant total adults. Hope that helps
