### ISSUE TITLE
Floating information boxes cut off information

### ISSUE THREAD

**Issue by curstwist** [Dwarf-Therapist/Dwarf-Therapist#272]
The information boxes for dwarfs when you hover over a name get cut off when there is a lot of information being listed.  
Windows 10, DF 50.05

Sample screenshot below:
![image](https://user-images.githubusercontent.com/39442864/211093166-32db2700-5aaa-45c6-9c46-03135873ca4c.png)

**Comment by cvuchener** [comment]
In Options → Tooltips, you have a few options to mitigate this. With "everybody does everything" becoming the default policy, this may become more common. A "Show only top X skills" option with a sane default may be necessary.

**Comment by OG-github** [comment]
I have the same problem. I tried everything that was suggested here even before I got to this page. There's still information that is being cut. Would be nice to have an option to leave the info window on screen and scroll somehow.
