### ISSUE TITLE
Unable to connect to game; windows x64 (Steam v50.05)

### ISSUE THREAD

**Issue by Mazz0690** [Dwarf-Therapist/Dwarf-Therapist#275]
My copy of Dwarf Therapist is not detecting my DF game instance. I have fort open, etc. I have tried deleting all directories for Dwarf Therapist (including appdata) and redownloading it. I have checked all the correct memory layouts are there. 

I do not have DF installed at the default Steam directory.

Here is my log

[dwarftherapist.log](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/10419418/dwarftherapist.log)

**Comment by cvuchener** [comment]
Important part of the log:

    INFO	core	PID of process is:  17328 [D:\a\Dwarf-Therapist\Dwarf-Therapist\src\dfinstancewindows.cpp:242] (DFInstanceWindows::find_running_copy)
    ERROR	core	Error opening process! "Access is denied." [D:\a\Dwarf-Therapist\Dwarf-Therapist\src\dfinstancewindows.cpp:250] (DFInstanceWindows::find_running_copy)

DF is detected but cannot be opened.

Which version of Windows are you using?
You say DF is not installed in Steam directory. Where is it? How do you start it?
Are you running DF and DT as the same user?
I don't recommend doing that for normal use, but does running DT as an administrator helps?

**Comment by Mazz0690** [comment]
Hi, It is installed in the steam directory, but not in the expected location (i.e. C:/Program Files/Steam/steamapps/common) as I have steam installed outside the program files directory, in the main directory of my C drive.
I am using Windows 10 64-bit. I am running both as the same user. 

Running as administrator appears to have solved the issue, so maybe it is to do with where I have the game installed.

If you need any other info please let me know,

thanks.

**Comment by cvuchener** [comment]
Could you [check if Dwarf Fortress.exe is running as administrator](https://superuser.com/questions/1213101/check-if-an-app-is-running-as-admin)? (it should not)

**Comment by Mazz0690** [comment]
No, DT opened normally without selecting run as administrator, is not running as an elevated process in the task manager.

**Comment by Mazz0690** [comment]
Update: I fully reinstalled steam and DF to the default location in the C drive and now Dwarf Therapist works properly.

**Comment by cvuchener** [comment]
> No, DT opened normally without selecting run as administrator, is not running as an elevated process in the task manager.

I meant DF not DT. If DF is admin, while DT is not, it cannot be opened.

Any way, you solved it.
