### ISSUE TITLE
Unable to see that a fort is loaded when running steam edition through wine

### ISSUE THREAD

**Issue by longtomjr** [Dwarf-Therapist/Dwarf-Therapist#277]
On 0.50 Steam, when running the game using wine (instead of proton), the game does not see that a fort is loaded.

Steps to reproduce (You might be able to skip the copy step):
1. Copy the `Dwarf Fortress` steam directory to somewhere that is not steam.
2. Run `Dwarf Fortress` by using `wine explorer` and navigating to the Dwarf Fortress copy, and run the `.exe`
3. Load a save
4. Try to connect via Dwarf-Therapist

I get the "A fort has not been loaded." error message. Output when running from a CLI:
```2023-Jan-17 22:32:40.563 INFO	core	Setting memory layout for DF checksum "0x63b6063b" [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstance.cpp:1097] (set_memory_layout)
2023-Jan-17 22:32:40.563 INFO	core	Detected Dwarf Fortress version "v0.50.05-steam sdl win64" using MemoryLayout from "/tmp/.mount_DwarfTTN8oVF/usr/share/dwarftherapist/memory_layouts/windows/v0.50.05_steam_win64.ini" [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstance.cpp:1103] (set_memory_layout)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x00000001412c1928" TO 0x7ffdd19b4e70 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x00000001412c1930" TO 0x7ffdd19b4e70 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x0000000141e14fe8" TO 0x7ffdd19b4d30 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x0000000141e14ff0" TO 0x7ffdd19b4d30 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x0000000141e14fd0" TO 0x7ffdd19b4d30 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.563 ERROR	core	READ_RAW: "Operation not permitted" READING 8 BYTES FROM "0x0000000141e14fd8" TO 0x7ffdd19b4d30 [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/dfinstancewine.cpp:114] (read_raw)
2023-Jan-17 22:32:40.573 WARNING	core	lost connection to DF [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/mainwindow.cpp:399] (lost_df_connection)
2023-Jan-17 22:32:40.573 ERROR	core	("No Game Loaded", "A fort has not been loaded.", "", "") [/home/runner/work/Dwarf-Therapist/Dwarf-Therapist/src/mainwindow.cpp:422] (lost_df_connection)
```

The reason for the roundabout way of opening DF is because that is the only way with DFHack that seems to currently work when launching via Wine (otherwise DFHack does not start correctly).

**Comment by cvuchener** [comment]
You mean it works with proton but not with another wine version?

What is your distribution? Wine version?
Make sure `ptrace_scope` is 0.

**Comment by longtomjr** [comment]
Thanks for the reply. I will be able to post more info from home later today.

> You mean it works with proton but not with another wine version?

Yes, it works when running it with proton, through steam, but running the game using wine (with the above method, outside of steam) gives that error.

Distro is EndeavourOS (so arch), my packages is (as of yesterday) up to date. Wine version should be [`wine 7.22-1`](https://archlinux.org/packages/multilib/x86_64/wine/). I will update if that is incorrect.

I will set the ptrace permission when I get home and report back. (For folks with a similar issue, see: https://wiki.archlinux.org/title/Dwarf_Fortress#Dwarf_Therapist on how to change that)

I will let you know once I have more information.

As an aside, I have been using Dwarf Therapist on steam, and apart from the #274 workaround, everything has been working well for my use (mostly as a live spreadsheet of my dwarfs, and to manage military squads and migration waves).

**Comment by cvuchener** [comment]
> I will set the ptrace permission when I get home and report back. (For folks with a similar issue, see: https://wiki.archlinux.org/title/Dwarf_Fortress#Dwarf_Therapist on how to change that)

setcap won't work with the AppImage because the actual binary is inside the image. If you want to use this method build Dwarf Therapist yourself, or [extract the AppImage](https://docs.appimage.org/user-guide/run-appimages.html#extract-the-contents-of-an-appimage)

An alternative you may want to try is building this small library
```
gcc -xc -m64 -Wall -fPIC -shared - -o set_ptracer_any.so << EOF
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <sys/prctl.h>
void set_ptracer_any() __attribute__((constructor));
void set_ptracer_any()
{
	if (-1 == prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY, 0, 0, 0))
		perror("prctl");
}
EOF
```
And preload the resulting `set_ptracer_any.so` library when running DF. It will allow debugging for the applications loading it. I think it is a better security than adding capabilities to DT. I did not test this with Wine but it may work.

It is surprising that it works with proton with `ptrace_scope` enabled. I wonder if steam does something to enable debugging.

**Comment by longtomjr** [comment]
Ok, thanks for that. I assumed that I would have to extract the appimage, but I can also just use the `-git` aur pkgbuild to build and install, since the PR was merged. I will try preloading the library first to see if that works.

I will play around a bit to see why it works with steam proton fine, but not with base wine.

**Comment by cvuchener** [comment]
I checked with strace, steam/proton does call `prctl(PR_SET_PTRACER, PR_SET_PTRACER_ANY)`.

**Comment by cvuchener** [comment]
I think the difference between Wine and Proton is there: https://github.com/ValveSoftware/wine/commit/dcc7655978f00ec4aa6a643b3988e7b1f5b4605d

**Comment by longtomjr** [comment]
Ok, so i am home now to test, and it seems like the issue is the appimage, not ptrace. I just built Dwarf Therapist locally from the latest git, and it connects fine for DF running through wine as described above.

**Comment by longtomjr** [comment]
Ok, I did another test, extracting the appimage, and then running the `dwarftherapist` binary from the filesystem (I assume that is the correct way, I am not super familiar with appimages) also fails to connect.

**Comment by cvuchener** [comment]
> Ok, so i am home now to test, and it seems like the issue is the appimage, not ptrace. I just built Dwarf Therapist locally from the latest git, and it connects fine for DF running through wine as described above.

With ptrace_scope set to 1, it does not work for me. Also the `LD_PRELOAD=set_ptracer_any.so` trick does not work, the ptracer must be overwritten by wine.

> Ok, I did another test, extracting the appimage, and then running the `dwarftherapist` binary from the filesystem (I assume that is the correct way, I am not super familiar with appimages) also fails to connect, same as when running the appimage directly.

You need to run it through AppRun, or set some environment variable like LD_LIBRARY_PATH and XDG_DATA_DIRS and maybe others.

**Comment by longtomjr** [comment]
The LD_PRELOAD does not get set because of this I think:
```
ERROR: ld.so: object '/home/hewert/bin/set_ptracer_any.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
ERROR: ld.so: object '/home/hewert/bin/set_ptracer_any.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
```

So to just correct my mistake from above, the reason the pkgbuild worked is because it sets the capability. It is not appimage related.

**Comment by longtomjr** [comment]
> The LD_PRELOAD does not get set because of this I think:
> 
> ```
> ERROR: ld.so: object '/home/hewert/bin/set_ptracer_any.so' from LD_PRELOAD cannot be preloaded (wrong ELF class: ELFCLASS64): ignored.
> ERROR: ld.so: object '/home/hewert/bin/set_ptracer_any.so' from LD_PRELOAD cannot be preloaded (wrong ELF class:
> ```

This is likely incorrect, since I think wine still prints that error even if it loads correctly, because it might be running 32bit binaries as well.
> ptracer must be overwritten by wine.

That is probably correct, sorry for the confusion.

**Comment by longtomjr** [comment]
Since we found out what the issue is, feel free to close the ticket. I will probably continue poking around for a bit to see if there is a way to set wine to allow ptrace, instead of setting the system-wide capability for Dwarf Therapist.

**Comment by cvuchener** [comment]
This wine support is temporary anyway. It will be reverted when DF for linux is released. I mostly added for myself, so I could continue develop in a linux environment. I won't make huge efforts to fix it.

**Comment by longtomjr** [comment]
Thanks for all the support and help, and for the great tool!
