### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by AndrielChaoti** [Dwarf-Therapist/Dwarf-Therapist#278]
I get an error whenever I launch dwarf therapist stating that it cannot check for updates because of the following issues:
v50 test1, but I've also experienced this issue in the current full release as well.

![image](https://user-images.githubusercontent.com/3628387/213845700-5963e257-73b0-4919-aa0a-9538e70338e2.png)

**Comment by cvuchener** [comment]
Try installing/updating OpenSSL 1.1. Or disable the updater if you don't care.

**Comment by AndrielChaoti** [comment]
I guess I'll just disable the updater, I'm not building perl to build openSSL to automatically update one program on a windows machine. thanks.

**Comment by cvuchener** [comment]
You can download pre-compiled binaries https://wiki.openssl.org/index.php/Binaries

**Comment by AndrielChaoti** [comment]
seems to have resolved the issue.
