### ISSUE TITLE
Linux/QT5.9.3: Extreme padding between columns in skill table

### ISSUE THREAD

**Issue by anders-larsson** [Dwarf-Therapist/Dwarf-Therapist#28]
Hi,

On Linux with QT5.9.3 Dwarf Therapist looks bad because of the padding between the different columns. It's also taking up a lot of space making it harder to use Dwarf Therapist. I have never seen it look like this before (when using Splintermind's version) so it's probably caused by the QT version?. Text also seems to be a bit blurry. Not sure if it's my system's fault though. See image linked below.

http://tinyimg.io/i/HyCoR1e.png

Thanks,

**Comment by cvuchener** [comment]
Also happening to @feelotraveller ([forum post](http://www.bay12forums.com/smf/index.php?topic=168411.msg7634040#msg7634040)), and myself with MSVC/Qt 5.9.3 on Windows. I would prefer to debug on Linux, but my fedora is still using 5.9.2.

**Comment by anders-larsson** [comment]
@cvuchener @feelotraveller: I found a "fix" for this issue. Deleting your saved User settings: File -> Clear User Settings.

Image: http://tinyimg.io/i/XkIJS2i.png

**Comment by feelotraveller** [comment]
Hm, Clear User Settings makes no graphic difference for me.  (It does delete my customisations.)
