### ISSUE TITLE
[v50] request to report unknown thought

### ISSUE THREAD

**Issue by emmahyde** [Dwarf-Therapist/Dwarf-Therapist#282]
<details>
<summary>Screenshots</summary>

![zrV8slY9wT](https://user-images.githubusercontent.com/8183738/215764154-30129d61-6575-4d1c-a823-35b47a23cb45.jpg)
![Dwarf_Fortress_XzGX7azyLx](https://user-images.githubusercontent.com/8183738/215764159-d35d3a21-4620-418c-89d9-cc959e7c7798.jpg)

</details>

The unknown thought here is self-pity.

**Comment by cvuchener** [comment]
Which version are you using? This should already be fixed.

**Comment by emmahyde** [comment]
Sorry about that! just updated. Closing.
