### ISSUE TITLE
Rage: Please Report

### ISSUE THREAD

**Issue by DeathCamel58** [Dwarf-Therapist/Dwarf-Therapist#284]
I was using Dwarf Therapist 41.2.5 on Linux with Dwarf Fortress v0.50.05-steam (DFHack 50.05-alpha3.1) when I inspected the happiness of my dwarfs. One of them is experiencing `rage`, and the popup asked me to report this.

Picture of the Dwarf Therapist popup asking for me to report this.
![image](https://user-images.githubusercontent.com/37940282/217288940-27712a26-85d4-4c5d-beb9-42ba83d80965.png)

**Comment by cvuchener** [comment]
Already fixed, please use the latest version.
