### ISSUE TITLE
Cannot see visitors

### ISSUE THREAD

**Issue by Lowkeyyyyyyy** [Dwarf-Therapist/Dwarf-Therapist#286]
Currently visitors does not show up in any of the pages.

It would be very useful for figuring out whom is a good candidate for petitions to stay in the fortress.
The current process without Therapist is very cumbersome.

**Comment by cvuchener** [comment]
Options → General → uncheck "Don't Display Visitors/Guests"

**Comment by Lowkeyyyyyyy** [comment]
This has no effect on the views for me atleast.

**Comment by cvuchener** [comment]
I forgot: and refresh the unit list ("Read" button).

If this still does not work, this is a bug I cannot reproduce. Make sure you have the latest version. Look in the logs (File → Open log directory) if you can find a reason your visitors are ignored (the log may contain spoilers).
