### ISSUE TITLE
Doesn't work with 50.07

### ISSUE THREAD

**Issue by viseatavist** [Dwarf-Therapist/Dwarf-Therapist#289]
Says version mismatch

**Comment by ri0t** [comment]
https://raw.githubusercontent.com/cvuchener/Dwarf-Therapist/583af59cb5a04f31b737ffa18d91ae60e7dcb725/share/memory_layouts/windows/v0.50.07-steam_win64.ini

Add this to your DT's memory_layouts folder. With it, i can connect and read dwarves, but not change anything.

**Comment by nielslynggaard** [comment]
Having the same issue.. Hopefully it will get fixed proper?

**Comment by cvuchener** [comment]
There was no release claiming to support 50.07. Wait for the next release. It will likely be soon.

**Comment by 2541750004** [comment]
> https://raw.githubusercontent.com/cvuchener/Dwarf-Therapist/583af59cb5a04f31b737ffa18d91ae60e7dcb725/share/memory_layouts/windows/v0.50.07-steam_win64.ini
> 
> 将其添加到DT的memory_layouts文件夹中。有了它，我可以连接和阅读矮人，但不会改变任何东西。

my dwarf hero
