### ISSUE TITLE
Add support for v50.09+

### ISSUE THREAD

**Issue by OmnesPotens** [Dwarf-Therapist/Dwarf-Therapist#298]
As the title says v50.09 which was released yesterday is not supported. It doesn't seem like that much has changed for Dwarf Therapist compatibility though so ideally will be a quick add. There is an experimental multi-threading setting that could cause issues, but I don't know the technicalities of what is being multi-threaded or if Dwarf Therapist will even be effected by this setting.

**Comment by Liriel-666** [comment]
please a working version for  windows
