### ISSUE TITLE
New squad members don't always equip gear.

### ISSUE THREAD

**Issue by donhth** [Dwarf-Therapist/Dwarf-Therapist#308]
Steps to reproduce:

1) Create a squad in df.
2) Assign a uniform.
3) Set schedule to equip/always.
4) Add squad members via dt.

May have to shuffle members around between squads to get the glitchy behavior to pop.

Some dorfs will remain naked and not equip until you go to df and click the 'Confirm' button in the Details window for a squad member. Iirc doing this will also trigger other unequipped members to equip. 

Could possibly be a bug in df. I haven't seen it happen in game yet, but that being said, I usually use dt.

It doesn't always happen. I use dt extensively for squad management. In my 130 dorf fort, most of of them are in active/inactive squads, and I move stressed out dorfs into their own special squad.

**Comment by cvuchener** [comment]
Is it an old issue or did it change in one of the recent versions? Equipment used to have weird behavior, even without DT. But maybe it was fixed in DF and DT did not follow the new procedure. It only sets `pickup_flags.update`. I cannot find anything assigning squad in DFHack to compare to. I may have to do some reversing to find how the game handles that.

**Comment by donhth** [comment]
I don't believe this is the same thing as the old odd equipment behavior. 

I've been playing df for a long time and have not experienced this type of behavior so frequently until recently.  It doesn't occur all the time which leans me to think it could be a df problem. And my bad, I have not tested that this is still the case in df latest version. It's been a few days since I've played.

**Comment by cvuchener** [comment]
I don't see the game setting `pickup_flags.update` (or any other flag in this group).

But it sets both the squad's `ammo.update` and the global `plotinfo.equipment.update` with `0x7ff` (all equipment flags).

**Comment by donhth** [comment]
Thanks! Will try it out.
