### ISSUE TITLE
Enhancements/Changes

### ISSUE THREAD

**Issue by donhth** [Dwarf-Therapist/Dwarf-Therapist#309]
Add a show/Bring to front button to pull up the df window for people like me connectiong remotely or using a single screen.

The deconstruction labor I believe is inapplicable. It appears to be associated with the mining labor. Likewise the mechanic labor is needed to destruct traps. There's probably other labors that don't apply anymore.

Ideally, I'd like to also see a button or have a hotkey in df that also pulls up the dt window. But that would need to be in a script (if that's possible) or a plugin.

**Comment by cvuchener** [comment]
That's your window manager job. Hotkey is Alt+Tab on Windows and most Linux desktop.
