### ISSUE TITLE
Linux 50.10 "A fort has not been loaded."

### ISSUE THREAD

**Issue by CEHA** [Dwarf-Therapist/Dwarf-Therapist#310]
I'm build this verssion https://github.com/cvuchener/Dwarf-Therapist/tree/50.10-linux
DF 50.10 Stem or Classic.

"A fort has not  been loaded."

OS - Debian Trixie

**Comment by cvuchener** [comment]
It should be fixed now. If you have more issues, please comment on the PR #305 .
