### ISSUE TITLE
Latest release does not connect to DF 50.11

### ISSUE THREAD

**Issue by ConanODoyle** [Dwarf-Therapist/Dwarf-Therapist#312]
The 50.11 update patch broke dwarf therapist as its not part of the working list of versions, despite not changing any of the memory locations of things (according to the update notes/dfhack). Adding the latest version to the list should work?

**Comment by ConanODoyle** [comment]
Somehow only now noticed the experimental layouts on the main support thread, which successfully loaded the Steam version. Closing until I run into issues.

**Comment by BirdMachine** [comment]
Including [a link here](http://www.bay12forums.com/smf/index.php?topic=168411.msg8504772#msg8504772) to make life easier for us all hunting it down :tada:

**Comment by ConanODoyle** [comment]
For anyone wondering how to install the experimental memory layout, you can just put the file directly in /data/memory_layouts/[operating system]
