### ISSUE TITLE
Unable to connect to the game. Steam Deck

### ISSUE THREAD

**Issue by Rastorkan** [Dwarf-Therapist/Dwarf-Therapist#315]
Dwarf Therapist doesn't see the running game. Win version of DT and latest release of DF without any forced compatibilities. Can't connect even with entered PID, taken from task manager.
![camphoto_1483920592](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/156260401/1bd4a7de-7f69-48ec-a997-019429f9aec0)

**Comment by Rastorkan** [comment]
> You need the linux version of DT to use with the linux version of DF. You may also need to change your ptrace_scope mode to 0, or you could try this: [#302 (comment)](https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/302#issuecomment-1770419676).

Thank you for a response! Steam is installing the win version by default, and I didn't see any options during installation. As well as linux version of Therapist shows an error about thta he can't find any linux dwarf fortress, while win therapist has a problem only with question if the game is running now.

So far i'm trying to successfully change the ptrace-scope to 0, let's see, maybe it will work. At least i'm sore that now it is set to 1 by default, so I hope this script will help me. Wether If it will help or it will not, I will write a comment here.

**Comment by Rastorkan** [comment]
> You need the linux version of DT to use with the linux version of DF. You may also need to change your ptrace_scope mode to 0, or you could try this: [#302 (comment)](https://github.com/Dwarf-Therapist/Dwarf-Therapist/issues/302#issuecomment-1770419676).

So, i tried different things, and I'm not sure what is the main problem, or maybe I'm just doing something wrong.
![IMG_2023](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/156260401/d6c4e40e-22aa-4023-a7b5-994331196784)


![IMG_2024](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/156260401/e23b02f1-60fd-4354-b195-ff0f21aaf2b3)

**Comment by cvuchener** [comment]
I guess SteamOS is not a great platform for development. Did you try running with the Steam Linux Runtime forced?

**Comment by cvuchener** [comment]
Or try this version I compiled on Fedora.
[set_ptracer_any.zip](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/13906695/set_ptracer_any.zip)

**Comment by Rastorkan** [comment]
> Or try this version I compiled on Fedora. [set_ptracer_any.zip](https://github.com/Dwarf-Therapist/Dwarf-Therapist/files/13906695/set_ptracer_any.zip)

Thank you so much for help and responses. I moved the .so file to root game directory and put the required launch command in steam game properties, but issue is still the same(

**Comment by Rastorkan** [comment]
> I guess SteamOS is not a great platform for development. Did you try running with the Steam Linux Runtime forced?

With forced Linux Runtime game just don't load the save. Maybe I have to try to install the Linux version somehow, but I really couldn't find any solutions for this via Steam.

**Comment by Rastorkan** [comment]
I found a ptrace file in the system, but I can't change the variable inside. Is there any ideas? It asks me for a password for permission, and after I put same password as for any command in Konsole (Terminal) it tells me that I'm not allowed
![IMG_2026](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/156260401/db482459-2c4e-467a-89b4-9e37e9cb5c0c)

**Comment by cvuchener** [comment]
If you want to change ptrace_scope permanently, you need to add a file in /etc/sysctl.d/ with .conf extension containing `kernel.yama.ptrace_scope = 0` (see [man sysctl.conf](https://man7.org/linux/man-pages/man5/sysctl.conf.5.html)).

**Comment by Rastorkan** [comment]
> If you want to change ptrace_scope permanently, you need to add a file in /etc/sysctl.d/ with .conf extension containing `kernel.yama.ptrace_scope = 0` (see [man sysctl.conf](https://man7.org/linux/man-pages/man5/sysctl.conf.5.html)).

Thanks for all the suggests! The problem was maximum silly. On Linux Runtime just for some reason won't launch the save that was from vannila compatibility. I created a new world, embarked, and straight after linux version of Dwarf Therapist connected to the session. Thanks a lot!

**Comment by MaikuMori** [comment]
For anyone looking at this. The save files are cross-platform and should work.
