### ISSUE TITLE
Request - Support for Spellcrafts familiars

### ISSUE THREAD

**Issue by Hiranus** [Dwarf-Therapist/Dwarf-Therapist#316]
As in title, I would like to request support for Spellcrafts mod familiars

https://steamcommunity.com/sharedfiles/filedetails/?id=2907539565

They are far weaker versions of "normal" dwarfs that cant do many labors like crafting, mining etc. but there are some labors that they can do, and it would be great to be able to manage those via therapist instead of managing it by  game work orders.

**Comment by Hiranus** [comment]
Actually, It seems like managing dwarfs by therapist and familiars by in-game labor menu is dumb to say the least. I already wiped my dwarf settings more than once.

**Comment by cvuchener** [comment]
Can you describe what would be needed to support this kind of mods? What is the issue with the current version?

**Comment by Hiranus** [comment]
Game sees familiars as citizens that are tamed, however dfhack doesn't see
them as citizens at all. I will provide more details today
evening/tomorrow.
Quick and dirty solution would be to allow us to change jobs of any
creature that is capable of having them that is not outright defined as
animal, regardless if it's tamed or trained, as long as it belongs to my
civ. This should allow me to manage familiars, and since we are talking
about mods ability to assign jobs to captured cave dwellers won't really be
an issue.
This should be locked behind some checkbox buried in options, as doing this
in vanilla may be weird.

sob., 20 sty 2024, 11:14 użytkownik Clément Vuchener <
***@***.***> napisał:

**Comment by cvuchener** [comment]
The current definition of "animal" in DT is : `(not CAN_LEARN) and (TRAINABLE_WAR or TRAINABLE_HUNT or PET or PET_EXOTIC)`. I think I should remove the `TRAINABLE` flags from this. And maybe even make it ` (not CAN_LEARN) or PET or PET_EXOTIC`. The division between animals and non-animals in DT is too strict, and it is hard to find a definition that works for everyone.

Maybe the best solution for your use case would be to create a custom grid view for labors but with "animals only" checked. Can you toggle the labors there?

**Comment by cvuchener** [comment]
> Maybe the best solution for your use case would be to create a custom grid view for labors but with "animals only" checked. Can you toggle the labors there?

Actually it won't work.

https://github.com/Dwarf-Therapist/Dwarf-Therapist/blob/9848ec9c3d92b970a856b67d3bdde3be10a291cd/src/dwarf.cpp#L1095-L1100

**Comment by Hiranus** [comment]
Here are the differences between normal animal (left), familiar (center) and dwarf (right) as seen by DFHack gui/gm-editor
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/6f8619a8-f957-4055-bddc-823eb10f34ce)
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/e7a7d9e3-b9b3-4524-bfaf-ed63d310b18a)
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/0ac0d54f-2acc-49b5-87d2-c68a261930a0)
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/fb303bfc-9c3e-464c-9809-892b116058ad)
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/3c962559-088a-4b21-9d7a-cb6962757c6e)

I see familiars in Labor menu and I can change their work there
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/764581e1-0cf5-4c67-bfc6-cb4d32208f4f)
I can also assign them to a workshop
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/f653694e-88d6-43e0-9c72-c235ec2995c0)
I see them as tamed citizens rather than pets
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/56b6400e-1a29-41c6-a3b8-fbfef14b9f3f)
Familiars can't be assigned to be nobles
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/5d2075a5-d28e-4966-92de-63a5bf57f50d)

**Comment by cvuchener** [comment]
I tested the mod, and I realize I misunderstood the issue. I thought the familiars were shown in "animal-only" views, but they are correctly categorize as non-animal. But labor cannot be toggled because they are "non-citizens". And they are not citizens because they don't have a historical figure id for checking fortress membership.

**Comment by Hiranus** [comment]
Do you think this scenario could be handled by DT?

niedz., 21 sty 2024, 00:39 użytkownik Clément Vuchener <
***@***.***> napisał:

**Comment by Hiranus** [comment]
When do you think you could release fix for this? I wouldn't mind some build done by you on the side just so I could manage dwarfs and familiars. Doing it by DFHack and assigning jobs to each familiar is one by one is awful.

**Comment by cvuchener** [comment]
Here [v42.1.3](https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v42.1.3)
