### ISSUE TITLE
Spellcrafts familiar - strange behaviors added by fix

### ISSUE THREAD

**Issue by Hiranus** [Dwarf-Therapist/Dwarf-Therapist#318]
Thank you for Spellcrafts familiars fix, but some new strange behaviors appeared due to fix. I don't think everything is easily solvable, but I will report them. Ideally, I would love fix to first thing, as I can easily live with other 2.

Tirist (familiar) is my expert cook, and he crafted masterwork quality meals. Crafting masterwork item turns anything into historical figure, which for some reason made him invisible in therapist.
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/1f304fc2-34d2-4318-8022-80460a14ed24)
When I remove his historical figure status via dfhack he is visible again
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/052fceec-5b43-4514-8bdd-b6d37a66cdbe)

It is possible to assign familiars to squads via therapist, despite it being impossible via in game menu.
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/5db91a74-1711-4bbd-aa42-e9df6bf423ae)
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/82cefff9-e0e0-40bd-b28a-d64d96b5f825)
Familiars assigned to squad via therapist are not visible in squad view, but they will still go on missions. This can fortunately be easily "fixed" by removing familiar from squad via therapist.
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/d0edd597-16f3-4eda-bb89-2d7ebffc5ec3)

Fix made captured sentient creatures visible in therapist, even if they are not tamed. This can lead to some interesting consequences so maybe don't fix this? At least hide this behind some option in menu please.
![obraz](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/6943031/e10ae01b-9ebe-4e9c-813d-364f87a807f8)

**Comment by cvuchener** [comment]
It is what I feared. Fixing this will require more effort and I am not sure I want to do it. Maybe I'll revert the patch and make the cheat option apply to more units instead.

**Comment by Hiranus** [comment]
Any update on this?

**Comment by cvuchener** [comment]
https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v42.1.4
http://www.bay12forums.com/smf/index.php?topic=168411.msg8529425#msg8529425

> The change from the last version had too many side-effects, so I reverted it and instead made labor cheat option apply to more units. You will have to display visitors to see units mislabeled as "non-citizens".
