### ISSUE TITLE
In game labors dont match therapist

### ISSUE THREAD

**Issue by gr33nhub** [Dwarf-Therapist/Dwarf-Therapist#320]
I use v0.50.11 win64 steam

Some of the labors dont match the selection in game.

Under work details -> Add new work detail, select Leatherworking and make the dwarf to specialize only do taks that match workshop assignments, work details and occupations.
Reload therapist and only Tanning is selected, not Leatherworking.

See Rovod Oggoden in the picture.

![DF](https://github.com/Dwarf-Therapist/Dwarf-Therapist/assets/16436376/8cea836d-90d0-48e6-a9a6-5a35dcc15183)

**Comment by cvuchener** [comment]
DT 41.2.2 is not compatible with DF 50.x, update Dwarf Therapist.
