### ISSUE TITLE
Add memory layouts for 50.12

### ISSUE THREAD

**Issue by CheeseCriminal** [Dwarf-Therapist/Dwarf-Therapist#321]
Add memory layouts for 50.12 please and thank you. 

If there is a way for me to do it I would love to learn but possibly easier / faster for someone with more experience. 

anyway, we need em.

**Comment by cvuchener** [comment]
In DFHack command prompt, run `devel/export-dt-ini`. This will create a file named `therapist.ini` in DF root directory, move it to `%APPDATA%/Roaming/Dwarf Therapist/memory_layouts/windows` on Windows or `~/.local/share/dwarftherapist/memory_layouts/linux` on Linux.

**Comment by CheeseCriminal** [comment]
Awesome! thank you

**Comment by Kuboczoch** [comment]
> In DFHack command prompt, run `devel/export-dt-ini`. This will create a file named `therapist.ini` in DF root directory, move it to `%APPDATA%/Roaming/Dwarf Therapist/memory_layouts/windows` on Windows or `~/.local/share/dwarftherapist/memory_layouts/linux` on Linux.

### I can confirm. This solution works for **v0.50.13** with DT version **42.1.0**.

It would be useful to have this info in the dwarf therapist directly tho

**Comment by Kuboczoch** [comment]
> 50.13 is already added: https://github.com/Dwarf-Therapist/Dwarf-Therapist/releases/tag/v42.1.6

But I downloaded the newest version of the DT, and it was incompatible with my Dwarf Fortress v0.50.13
