### ISSUE TITLE
Leader seems to be taking Archer as a defining factor.

### ISSUE THREAD

**Issue by Oafsalot** [Dwarf-Therapist/Dwarf-Therapist#327]
I noticed this as my Melee Squads had a much lower Teacher than the game reported.

![image](https://github.com/user-attachments/assets/2881edeb-a68a-453b-ba9a-a4682ade13c4)

Does this mean that the Teacher is taking Archer as a relevant skill? And should it?

**Comment by cvuchener** [comment]
This means the Teacher role is broken, it should obviously use the Teacher skill.
