### ISSUE TITLE
Missing profession icons

### ISSUE THREAD

**Issue by cvuchener** [Dwarf-Therapist/Dwarf-Therapist#35]
Profession icons are located in [resources/img/profession icons/](https://github.com/Dwarf-Therapist/Dwarf-Therapist/tree/master/resources/img/profession%20icons)

- [x] Monster Slayer (prof_107.png)
- [x] Scout (prof_108.png)
- [x] Beast Hunter (prof_109.png)
- [x] Snatcher (prof_110.png)
- [x] Mercenary (prof_111.png)
- [x] Performer (prof_113.png)
- [x] Poet (prof_114.png)
- [x] Bard (prof_115.png)
- [x] Dancer (prof_116.png)
- [x] Sage (prof_117.png)
- [x] Scholar (prof_118.png)
- [x] Philosopher (prof_119.png)
- [x] Mathematician (prof_120.png)
- [x] Historian (prof_121.png)
- [x] Astronomer (prof_122.png)
- [x] Naturalist (prof_123.png)
- [x] Chemist (prof_124.png)
- [x] Geographer (prof_125.png)
- [x] Scribe (prof_126.png)
- [x] Papermaker (prof_127.png)
- [x] Bookbinder (prof_128.png)
- [x] Tavern Keeper (prof_129.png)
- [x] Criminal (prof_130.png)
- [x] Peddler (prof_131.png)
- [x] Prophet (prof_132.png)
- [x] Pilgrim (prof_133.png)
- [x] Monk (prof_134.png)

**Comment by cvuchener** [comment]
Numbers were offset by one. Gelder was actually good, and Monster Slayer missing.

**Comment by fakemonster** [comment]
@cvuchener how's this? 
![prof_test](https://user-images.githubusercontent.com/17960118/36764466-9eb48586-1be1-11e8-9e6f-e9b0cb37d67f.png)
Wasn't sure if there was a particular imagery desired so I just went for it

**Comment by cvuchener** [comment]
It's good. Do you want to create a pull request or should I do it myself?

**Comment by fakemonster** [comment]
I'll go ahead and make a PR, just wanted to be sure the asset was OK first. Thanks!

**Comment by cvuchener** [comment]
Thanks, all current professions should have an icon now.
