### ISSUE TITLE
39.1.1 Mac Version crashes due to wrong library path

### ISSUE THREAD

**Issue by jobywalker** [Dwarf-Therapist/Dwarf-Therapist#41]
Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/Cellar/qt@5.7/5.7.1/lib/QtGui.framework/Versions/5/QtGui
  Referenced from: /Applications/Lazy Mac Pack v0.44.02-barebones-alpha-a/LNP/Utilities/DwarfTherapist.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
  Reason: image not found

**Comment by cvuchener** [comment]
Is this related to https://bugreports.qt.io/browse/QTBUG-56814? If it is I'll have to revert to Qt 5.5, Qt 5.10 requires OS X 10.11.

**Comment by jobywalker** [comment]
Yeah looks like https://bugreports.qt.io/browse/QTBUG-56814 could be the issue.  It is referencing the absolute path "/usr/local/Cellar/..." instead of loading from the DwarfTherapist.app's Framework directory.
