### ISSUE TITLE
What happened to sort by squad?

### ISSUE THREAD

**Issue by ldog** [Dwarf-Therapist/Dwarf-Therapist#56]
Military tab now sorted by sex and sexual orientation instead of squads.
Not useful. I can't seem to find the option to make it like it used to be.

**Comment by cvuchener** [comment]
I inserted a new group so the groups that come after changed value. That broke the stored setting but you should be able to re-select squad grouping in the drop down menu beside the ![category-group](https://github.com/Dwarf-Therapist/Dwarf-Therapist/raw/master/resources/img/category-group.png) icon.

**Comment by ldog** [comment]
SMH, yeah I'm an idiot. I haven't played in months and there's always a little relearning. Thanks!
