### ISSUE TITLE
Text size in Script Editor is extremely small

### ISSUE THREAD

**Issue by seanasy** [Dwarf-Therapist/Dwarf-Therapist#60]
MacOS 10.13.3
Dwarf Therapist 39.2.0

The text size in the Script Editor Help and and scripting documentation is almost unreadably small. The  size in the actual editor is pretty small too. Please, make the default bigger or make the size configurable.

![screen shot 2018-02-26 at 10 59 57 am](https://user-images.githubusercontent.com/5132749/36680609-38dee74a-1ae4-11e8-8892-4c877355db18.png)

**Comment by cvuchener** [comment]
The documentation font is small (8 pt) and I would not mind making it a little bigger. But, in your screenshot, it looks smaller than it should. The current style is trying to use a Microsoft font (MS Shell Dlg 2), could this cause the issue?

The editor font is the default size but forced to Courrier New. I should check if there is a way to use the system preferred monospace font.

**Comment by seanasy** [comment]
I think it is much smaller than 8pt. The typeface probably is the issue. The text for the other tabs has the same issue except in the tables. If those tables are using different typeface, that's likely the problem.

Specifying a more generic typeface would probably help. Arial (a Microsoft typeface) is included with MacOS. Courier New is common to both, as well.

![screen shot 2018-02-27 at 9 05 53 pm](https://user-images.githubusercontent.com/5132749/36766168-b90aea12-1c02-11e8-8a24-c7aeb0091a0c.png)

**Comment by cvuchener** [comment]
I completely changed how the styling is done when fixing some color issue I had with my dark theme. If you are able to compile DT, you could try the branch from PR #65 and see how it affects your text size. In the CSS stylesheet, font-size is set to "small" (I wanted to use percents but it does not work), and no font-family is set, it should use the system default.

**Comment by cvuchener** [comment]
It should be fixed with the new stylesheet.
