### ISSUE TITLE
[Feature request] Have "Try again" button on "Can't find dwarf fortress"

### ISSUE THREAD

**Issue by LittleEndu** [Dwarf-Therapist/Dwarf-Therapist#68]
When looking for specific embark you will burn through a'lot of worlds. Having to click 3 times to get therapist running again is too much.

**Comment by cvuchener** [comment]
Good suggestion.

It is actually almost already done. If "Automatically Connect" is enabled, it will try to reconnect after 5 seconds. If you also uncheck "Alert on Lost Connection", you can reconnect in zero click.

I should still add a "Retry" button that reconnect immediately even without "Automatically Connect" enabled.
