### ISSUE TITLE
Angle column headers for ease of reading

### ISSUE THREAD

**Issue by hrobertson** [Dwarf-Therapist/Dwarf-Therapist#71]
I would really appreciate the option to have column headers angled from the vertical.
Example image: https://i.stack.imgur.com/2VDhS.png
I think this would really improve the readability of the column headers.

If the text direction was set to Top to Bottom, they would be angled to the left. If Bottom to Top, then angled to the right as in the linked example.

Thanks!

**Comment by cvuchener** [comment]
Sorry, it is not something that Qt can do. The header must be the same width as the whole column and they cannot overlap.
