### ISSUE TITLE
Some dwarf thoughts/stress broken (44.10)

### ISSUE THREAD

**Issue by lucyviola** [Dwarf-Therapist/Dwarf-Therapist#90]
![image](https://user-images.githubusercontent.com/39748101/40689111-b38a5ac2-6398-11e8-9ff4-37e9e51e2171.png)
![image](https://user-images.githubusercontent.com/39748101/40689139-d4d5f8d0-6398-11e8-9843-ed2468a15aca.png)
There's a bit of a discrepancy between DF and DT when it comes to the new 'memories' stuff - DT not showing the difference between new stressors and past trauma is an extremely minor niggle, but the split between 'saw someone die' and 'saw a corpse' causes lots of 'this is an unknown thought, please report it' in DT.

**Comment by cvuchener** [comment]
I understand your dwarf was horrified by an unknown thought. It must be terrifying.

The missing thought must be the one from this dfhack issue: https://github.com/DFHack/df-structures/issues/255. It needs to be added in game_data.ini unit_thoughts section.

**Comment by lucyviola** [comment]
Alrighty then, closed since it's not your problem. Thanks for the fantastic work!

**Comment by cvuchener** [comment]
You can test [the new game_data.ini](https://raw.githubusercontent.com/cvuchener/Dwarf-Therapist/69301c3ea394b3aac0280b60256f7e561f3f35bf/resources/game_data.ini) by saving it in your data folder. You can find it by clicking "Open data directory" in the "File" menu. If you are using Windows the "data" folder in DT installation directory is good too. You will have to remember to delete it later so it does not override the future updates.

There are more missing thoughts in df-structures that I did not add yet (they don't have a caption):
```
209	DreamAbout
210	Dream
211	Nightmare
218	OpinionStoryteller
219	OpinionRecitation
220	OpinionInstrumentSimulation
221	OpinionInstrumentPlayer
222	OpinionSinger
223	OpinionChanter
224	OpinionDancer
225	OpinionStory
226	OpinionPoetry
227	OpinionMusic
228	OpinionDance
229	Defeated
230	FavoritePossession
231	PreserveBody
232	Murdered
233	HistEventCollection
234	ViewOwnDisplay
235	ViewDisplay
236	AcquireArtifact
237	DenySanctuary
238	CaughtSneaking
239	GaveArtifact
```
