### ISSUE TITLE
Importing professions ignores checkboxes

### ISSUE THREAD

**Issue by RadGH** [Dwarf-Therapist/Dwarf-Therapist#95]
Hi, I found a bug importing professions. The checkboxes to choose which ones to import doesn't seem to work. I share my professions publicly ([here](https://github.com/RadGH/RadGH-s-Dwarf-Therapist-Professions)) and this bug might cause issues for people who don't want particular professions.

**EDIT: I believe this also affects exporting professions in the same manner.**

1. Here are existing professions. I will be importing a copy that has a new profession "2: Builder" next.

![image](https://user-images.githubusercontent.com/2008464/41131380-5cb8f9c2-6a70-11e8-91c9-14ec2f71b7f1.png)

2. Importing my custom professions, you can see Builder here:

![image](https://user-images.githubusercontent.com/2008464/41131400-7894c05e-6a70-11e8-89ea-530ea6c9b389.png)

3. I unchecked Builder, I do NOT want to import it:

![image](https://user-images.githubusercontent.com/2008464/41131410-831321b0-6a70-11e8-8719-38557b8efa12.png)

4. Import successful, but 44 were imported? That number is off too. It only actually imported 1 profession, and it was not supposed to even do that!

![image](https://user-images.githubusercontent.com/2008464/41131436-9b2dc91c-6a70-11e8-96bc-7d15cc196d21.png)

5. Confirming that Builder was imported, erroneously:

![image](https://user-images.githubusercontent.com/2008464/41131451-ad691d0c-6a70-11e8-8570-5a2a6f44e535.png)

Thanks

**Comment by cvuchener** [comment]
Exporting looks good to me.
